"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BriefcaseBusiness, CalendarDays, MapPin, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getBackendApiRoot, getTenantHeaders } from "@/lib/runtime-context";
type Job={public_id:string;title:string;code:string;location?:string;workplace_type?:string;description:string;requirements?:string;deadline?:string;vacancies_count:number};
export default function CareersPage(){
 const[jobs,setJobs]=useState<Job[]>([]),[selected,setSelected]=useState<Job|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{fetch(getBackendApiRoot()+"/public/recruitment/jobs",{headers:{Accept:"application/json",...getTenantHeaders({allowUnsigned:true})}}).then(async r=>{if(!r.ok)throw new Error((await r.json()).message||"Unable to load vacancies.");return r.json()}).then(p=>setJobs(p.data||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function apply(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setMessage("");setError("");const form=event.currentTarget;const response=await fetch(getBackendApiRoot()+"/public/recruitment/jobs/"+selected.public_id+"/apply",{method:"POST",headers:{Accept:"application/json",...getTenantHeaders({allowUnsigned:true})},body:new FormData(form)});const payload=await response.json();if(!response.ok){setError(payload.message||"Application could not be submitted.");return}form.reset();setMessage("Application received. Your reference is "+payload.data.application_id+".")}
 return <main className="min-h-screen bg-slate-950 text-slate-100"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6">
  <Link href="/" className="inline-flex min-h-11 items-center gap-2 rounded-lg text-sm text-emerald-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-300"><ArrowLeft aria-hidden className="h-4 w-4"/>Back to company home</Link>
  <header className="mt-8 max-w-3xl"><p className="font-mono text-xs font-bold uppercase tracking-[.25em] text-emerald-300">Open opportunities</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">Do work that matters.</h1><p className="mt-4 text-lg leading-8 text-slate-300">Explore current vacancies and apply directly. Every application is reviewed by the hiring team.</p></header>
  {error&&<p role="alert" className="mt-6 rounded-xl border border-red-400 bg-red-950/50 p-4 text-red-100">{error}</p>}{message&&<p role="status" className="mt-6 rounded-xl border border-emerald-400 bg-emerald-950/50 p-4 text-emerald-100">{message}</p>}
  <div className="mt-10 grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><section aria-labelledby="vacancy-list-heading"><h2 id="vacancy-list-heading" className="sr-only">Current vacancies</h2><div className="space-y-3">
   {loading?<p>Loading vacancies…</p>:jobs.length===0?<p className="rounded-2xl border border-slate-500 p-6">There are no open vacancies right now.</p>:jobs.map(job=><button type="button" key={job.public_id} onClick={()=>setSelected(job)} className={"min-h-11 w-full rounded-2xl border p-5 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-300 "+(selected?.public_id===job.public_id?"border-emerald-400 bg-emerald-950/40":"border-slate-500 bg-slate-900 hover:border-slate-500")}><span className="flex items-start justify-between gap-4"><span><span className="block text-lg font-bold">{job.title}</span><span className="mt-2 flex flex-wrap gap-3 text-sm text-slate-300"><span className="inline-flex gap-1"><MapPin aria-hidden className="h-4 w-4"/>{job.location||"Location flexible"}</span><span>{job.workplace_type?.replaceAll("_"," ")}</span></span></span><BriefcaseBusiness aria-hidden className="h-5 w-5 text-emerald-300"/></span></button>)}
  </div></section><section aria-labelledby="vacancy-heading" className="rounded-3xl border border-slate-500 bg-slate-900 p-6 sm:p-8">
   {!selected?<div className="grid min-h-72 place-items-center text-center text-slate-400">Select a vacancy to view details and apply.</div>:<><h2 id="vacancy-heading" className="text-3xl font-black">{selected.title}</h2><div className="mt-3 flex flex-wrap gap-4 text-sm text-slate-300"><span>{selected.code}</span><span>{selected.vacancies_count} opening(s)</span>{selected.deadline&&<span className="inline-flex gap-1"><CalendarDays aria-hidden className="h-4 w-4"/>Apply by {selected.deadline}</span>}</div><p className="mt-6 whitespace-pre-wrap text-slate-200">{selected.description}</p>{selected.requirements&&<><h3 className="mt-8 text-xl font-bold">What you’ll bring</h3><p className="mt-3 whitespace-pre-wrap text-slate-300">{selected.requirements}</p></>}
   <form onSubmit={apply} className="mt-10 space-y-5 border-t border-slate-500 pt-8"><h3 className="text-2xl font-black">Apply for this vacancy</h3>
    <div><Label htmlFor="candidate_name">Full name</Label><Input id="candidate_name" name="candidate_name" autoComplete="name" required className="mt-2 bg-slate-950"/></div>
    <div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="email">Email address</Label><Input id="email" name="email" type="email" autoComplete="email" required className="mt-2 bg-slate-950"/></div><div><Label htmlFor="phone">Phone number</Label><Input id="phone" name="phone" type="tel" autoComplete="tel" className="mt-2 bg-slate-950"/></div></div>
    <div><Label htmlFor="cover_letter">Why are you interested?</Label><textarea id="cover_letter" name="cover_letter" rows={5} className="mt-2 w-full rounded-md border border-slate-500 bg-slate-950 p-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-300"/></div>
    <div><Label htmlFor="resume">Resume (PDF or Word, up to 10 MB)</Label><Input id="resume" name="resume" type="file" accept=".pdf,.doc,.docx" className="mt-2 bg-slate-950"/></div>
    <label className="flex gap-3 text-sm text-slate-300"><input name="consent" value="1" type="checkbox" required className="mt-1 h-5 w-5"/><span>I consent to this tenant processing my application for recruitment purposes.</span></label>
    <Button type="submit" className="min-h-11 bg-emerald-700 hover:bg-emerald-800"><Send aria-hidden className="mr-2 h-4 w-4"/>Submit application</Button>
   </form></>}</section></div>
 </div></main>
}
