import { LayoutDashboard } from "lucide-react";
import {
  UsersRound,
  ShieldAlert,
  FileText,
  UserCheck,
  Network,
  Building2,
  BriefcaseBusiness,
  ShieldCheck,
  BookOpen,
  CalendarDays,
  Laptop,
  Receipt,
  Settings2,
  ArrowLeftRight,
  Sparkles,
  Gauge,
  GitBranch,
  GraduationCap,
  Plane,
  LogOut,
} from "lucide-react";
import type { FrontendModuleDefinition } from "@/modules/types";

export const humanResourcesModule: FrontendModuleDefinition = {
  id: "humanresources",
  name: "Human Resources",
  description:
    "Organization design, employee records, workforce assignments, and compliance.",
  backendModule: "Modules\\HumanResources",
  routePrefixes: [
    "/dashboard/human-resources",
    "/dashboard/human-resources/employees",
    "/dashboard/human-resources/transfers",
    "/dashboard/human-resources/relations",
    "/dashboard/human-resources/forms",
    "/dashboard/human-resources/profile",
    "/dashboard/human-resources/organigram",
    "/dashboard/human-resources/organization",
    "/dashboard/human-resources/positions",
    "/dashboard/human-resources/compliance",
    "/dashboard/human-resources/policies",
    "/dashboard/human-resources/leave",
    "/dashboard/vacancy-management",
    "/dashboard/human-resources/recruitment",
    "/dashboard/human-resources/appraisals",
    "/dashboard/human-resources/assets",
    "/dashboard/human-resources/expenses",
    "/dashboard/human-resources/settings",
    "/dashboard/human-resources/talent",
    "/dashboard/human-resources/talent/competencies",
    "/dashboard/human-resources/talent/succession",
    "/dashboard/human-resources/talent/training",
    "/dashboard/human-resources/talent/travel",
    "/dashboard/human-resources/talent/offboarding",
  ],
  navItems: [
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_dashboard",
      fallbackLabel: "HR Dashboard",
      href: "/dashboard/human-resources",
      icon: LayoutDashboard,
      subscriptionSlug: "human_resources",
      permissions: ["view_employees", "manage_employees"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_employees",
      fallbackLabel: "Employees Directory",
      href: "/dashboard/human-resources/employees",
      icon: UsersRound,
      subscriptionSlug: "human_resources",
      permissions: ["view_employees", "manage_employees"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_transfers",
      fallbackLabel: "Employee Transfers",
      href: "/dashboard/human-resources/transfers",
      icon: ArrowLeftRight,
      subscriptionSlug: "human_resources",
      permissions: ["view_employees", "manage_employees"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_relations",
      fallbackLabel: "Employee Relations",
      href: "/dashboard/human-resources/relations",
      icon: ShieldAlert,
      subscriptionSlug: "human_resources",
      permissions: ["view_employee_relations", "manage_employee_relations"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_forms",
      fallbackLabel: "HR Forms & Generator",
      href: "/dashboard/human-resources/forms",
      icon: FileText,
      subscriptionSlug: "human_resources",
      permissions: ["view_hr_forms", "generate_hr_forms"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_profile",
      fallbackLabel: "Employee Profile 360",
      href: "/dashboard/human-resources/profile",
      icon: UserCheck,
      subscriptionSlug: "human_resources",
      permissions: ["view_employee_profile", "edit_own_profile"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_organigram",
      fallbackLabel: "Organigram Tree",
      href: "/dashboard/human-resources/organigram",
      icon: Network,
      subscriptionSlug: "human_resources",
      permissions: ["view_organigram", "manage_organigram"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_organization",
      fallbackLabel: "Organization Units",
      href: "/dashboard/human-resources/organization",
      icon: Building2,
      subscriptionSlug: "human_resources",
      permissions: ["view_hr_organization", "manage_hr_organization"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_positions",
      fallbackLabel: "Positions Control",
      href: "/dashboard/human-resources/positions",
      icon: BriefcaseBusiness,
      subscriptionSlug: "human_resources",
      permissions: ["view_hr_positions", "manage_hr_positions"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_compliance",
      fallbackLabel: "Labour Compliance",
      href: "/dashboard/human-resources/compliance",
      icon: ShieldCheck,
      subscriptionSlug: "human_resources",
      permissions: [
        "view_hr_compliance",
        "manage_hr_compliance",
        "review_hr_compliance_policies",
        "activate_hr_compliance_policies",
      ],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_policies",
      fallbackLabel: "HR Policies",
      href: "/dashboard/human-resources/policies",
      icon: BookOpen,
      subscriptionSlug: "human_resources",
      permissions: ["view_hr_policies", "manage_hr_policies"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_leave",
      fallbackLabel: "Leave Management",
      href: "/dashboard/human-resources/leave",
      icon: CalendarDays,
      subscriptionSlug: "human_resources",
      permissions: [
        "request_leave",
        "view_own_leave",
        "view_team_leave",
        "view_leave_requests",
        "approve_leave_requests",
      ],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.vacancy_management",
      fallbackLabel: "Vacancy & Assessments",
      href: "/dashboard/vacancy-management",
      icon: UserCheck,
      subscriptionSlug: "vacancy_management",
      permissions: ["view_recruitment", "manage_recruitment", "view_employees"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_assets",
      fallbackLabel: "Asset Custody",
      href: "/dashboard/human-resources/assets",
      icon: Laptop,
      subscriptionSlug: "human_resources",
      permissions: ["view_hr_assets", "manage_hr_assets", "view_employees"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_expenses",
      fallbackLabel: "Expense Claims",
      href: "/dashboard/human-resources/expenses",
      icon: Receipt,
      subscriptionSlug: "human_resources",
      permissions: ["view_hr_expenses", "manage_hr_expenses", "view_employees"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_talent",
      fallbackLabel: "Talent Management",
      href: "/dashboard/human-resources/talent",
      icon: Sparkles,
      subscriptionSlug: "human_resources",
      permissions: ["view_talent", "manage_talent", "view_employees"],
      placement: "primary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_competencies",
      fallbackLabel: "Competency Framework",
      href: "/dashboard/human-resources/talent/competencies",
      icon: Gauge,
      subscriptionSlug: "human_resources",
      permissions: ["view_talent", "manage_competencies", "assess_competencies", "manage_talent"],
      placement: "secondary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_succession",
      fallbackLabel: "Succession Planning",
      href: "/dashboard/human-resources/talent/succession",
      icon: GitBranch,
      subscriptionSlug: "human_resources",
      permissions: ["view_talent", "manage_succession", "manage_talent"],
      placement: "secondary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_training",
      fallbackLabel: "Training & Development",
      href: "/dashboard/human-resources/talent/training",
      icon: GraduationCap,
      subscriptionSlug: "human_resources",
      permissions: ["view_talent", "manage_training", "enrol_training", "manage_talent"],
      placement: "secondary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_travel",
      fallbackLabel: "Travel & Per Diem",
      href: "/dashboard/human-resources/talent/travel",
      icon: Plane,
      subscriptionSlug: "human_resources",
      permissions: ["view_talent", "request_travel", "approve_travel", "manage_travel", "manage_talent"],
      placement: "secondary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_offboarding",
      fallbackLabel: "Offboarding & Clearance",
      href: "/dashboard/human-resources/talent/offboarding",
      icon: LogOut,
      subscriptionSlug: "human_resources",
      permissions: [
        "view_talent",
        "manage_offboarding",
        "complete_offboarding_tasks",
        "settle_offboarding",
        "manage_talent",
      ],
      placement: "secondary",
    },
    {
      moduleId: "humanresources",
      translationKey: "nav.hr_settings",
      fallbackLabel: "HR Settings",
      href: "/dashboard/human-resources/settings",
      icon: Settings2,
      subscriptionSlug: "human_resources",
      permissions: ["view_hr_settings", "manage_hr_settings"],
      placement: "primary",
    },
  ],
};
