"use client";

import { useState, type FormEvent } from "react";
import { CalendarCheck2, MessageSquareText, Plus, TrendingUp } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";
import { performanceApi } from "@/modules/performance/api";
import type { Checkin, Feedback, ImprovementPlan, PerformanceReferences } from "@/modules/performance/types";
import { BusyLabel, PerformanceError, PerformanceLoading, PerformanceShell, PerformanceStatus, PerformanceTable } from "@/modules/performance/pages/components/performance-shell";

type Activity = "feedback" | "checkin" | "plan";

export default function PerformanceDevelopmentPage() {
  const [activity, setActivity] = useState<Activity | null>(null); const client = useQueryClient();
  const references = useQuery({ queryKey: ["performance", "references"], queryFn: performanceApi.references });
  const feedback = useQuery({ queryKey: ["performance", "feedback"], queryFn: () => performanceApi.feedback() });
  const checkins = useQuery({ queryKey: ["performance", "checkins"], queryFn: () => performanceApi.checkins() });
  const plans = useQuery({ queryKey: ["performance", "plans"], queryFn: () => performanceApi.plans() });
  const refresh = async () => { await client.invalidateQueries({ queryKey: ["performance"] }); };
  const feedbackMutation = useMutation({ mutationFn: performanceApi.createFeedback, onSuccess: async () => { await refresh(); setActivity(null); toast.success("Feedback saved."); }, onError: () => toast.error("Feedback could not be saved.") });
  const feedbackUpdate = useMutation({ mutationFn: ({ id, status }: { id: number; status: "declined" | "submitted" }) => performanceApi.updateFeedback(id, { status }), onSuccess: async () => { await refresh(); toast.success("Feedback status updated."); }, onError: () => toast.error("Feedback could not be updated.") });
  const checkinMutation = useMutation({ mutationFn: performanceApi.createCheckin, onSuccess: async () => { await refresh(); setActivity(null); toast.success("Check-in saved."); }, onError: () => toast.error("Check-in could not be saved.") });
  const checkinUpdate = useMutation({ mutationFn: (id: number) => performanceApi.updateCheckin(id, { status: "completed" }), onSuccess: async () => { await refresh(); toast.success("Check-in completed."); }, onError: () => toast.error("Check-in could not be completed.") });
  const planMutation = useMutation({ mutationFn: performanceApi.createPlan, onSuccess: async () => { await refresh(); setActivity(null); toast.success("Improvement plan saved."); }, onError: () => toast.error("Improvement plan could not be saved.") });
  const planAction = useMutation({ mutationFn: ({ id, action }: { id: number; action: "activate" | "acknowledge" | "successful" | "extend" | "unsuccessful" | "cancel" }) => performanceApi.planAction(id, action), onSuccess: async () => { await refresh(); toast.success("Improvement plan updated."); }, onError: () => toast.error("Improvement plan could not be updated.") });
  const loadingReferences = references.isLoading || !references.data;
  return <PerformanceShell title="Feedback and development" description="Keep performance continuous with requested feedback, manager check-ins, coaching support, and time-bound improvement plans.">
    <section aria-labelledby="add-development-activity"><div className="mb-3"><h2 id="add-development-activity" className="text-lg font-semibold">Add development activity</h2><p className="text-sm text-muted-foreground">Choose one activity. The selected form appears directly below.</p></div><div className="flex flex-wrap gap-2"><ActivityButton selected={activity === "feedback"} controls="feedback-form" onClick={() => setActivity(activity === "feedback" ? null : "feedback")} icon={MessageSquareText}>Feedback</ActivityButton><ActivityButton selected={activity === "checkin"} controls="checkin-form" onClick={() => setActivity(activity === "checkin" ? null : "checkin")} icon={CalendarCheck2}>Check-in</ActivityButton><ActivityButton selected={activity === "plan"} controls="improvement-plan-form" onClick={() => setActivity(activity === "plan" ? null : "plan")} icon={TrendingUp}>Improvement plan</ActivityButton></div></section>
    {activity && loadingReferences ? <PerformanceLoading cards={2} /> : null}
    {references.error ? <PerformanceError error={references.error} title="Employee references could not be loaded" /> : null}
    {activity === "feedback" && references.data ? <FeedbackForm references={references.data} busy={feedbackMutation.isPending} onSubmit={(payload) => feedbackMutation.mutate(payload)} /> : null}
    {activity === "checkin" && references.data ? <CheckinForm references={references.data} busy={checkinMutation.isPending} onSubmit={(payload) => checkinMutation.mutate(payload)} /> : null}
    {activity === "plan" && references.data ? <PlanForm references={references.data} busy={planMutation.isPending} onSubmit={(payload) => planMutation.mutate(payload)} /> : null}
    <Card><CardHeader><CardTitle><h2>Feedback exchange</h2></CardTitle><CardDescription>Requested and submitted feedback with controlled visibility.</CardDescription></CardHeader><CardContent>{feedback.isLoading ? <PerformanceLoading cards={2} /> : feedback.error || !feedback.data ? <PerformanceError error={feedback.error} /> : <PerformanceTable<Feedback> caption="Performance feedback requests and responses, newest first." rows={feedback.data.data} getKey={(row) => row.id} columns={[{ key: "subject", label: "Employee", render: (row) => row.subject?.primary_name ?? `Employee ${row.subject_employee_id}` }, { key: "relationship", label: "Perspective", render: (row) => row.relationship.replaceAll("_", " ") }, { key: "visibility", label: "Visibility", render: (row) => row.visibility.replaceAll("_", " ") }, { key: "status", label: "Status", render: (row) => <PerformanceStatus value={row.status} /> }, { key: "feedback", label: "Feedback", render: (row) => <span className="line-clamp-2 max-w-sm">{row.feedback || "Awaiting response"}</span> }, { key: "action", label: "Action", align: "right", render: (row) => row.status === "requested" ? <Button type="button" size="sm" variant="outline" disabled={feedbackUpdate.isPending} onClick={() => feedbackUpdate.mutate({ id: row.id, status: "declined" })}>Decline request</Button> : <span className="text-muted-foreground">Recorded</span> }]} />}</CardContent></Card>
    <Card><CardHeader><CardTitle><h2>Performance check-ins</h2></CardTitle><CardDescription>Planned and completed employee-manager coaching conversations.</CardDescription></CardHeader><CardContent>{checkins.isLoading ? <PerformanceLoading cards={2} /> : checkins.error || !checkins.data ? <PerformanceError error={checkins.error} /> : <PerformanceTable<Checkin> caption="Employee performance check-ins ordered by date." rows={checkins.data.data} getKey={(row) => row.id} columns={[{ key: "employee", label: "Employee", render: (row) => row.employee?.primary_name ?? `Employee ${row.employee_id}` }, { key: "date", label: "Date", render: (row) => row.checkin_on }, { key: "goal", label: "Goal", render: (row) => row.goal?.title ?? "General check-in" }, { key: "progress", label: "Progress", align: "right", render: (row) => row.progress_percent == null ? "—" : `${Number(row.progress_percent).toFixed(0)}%` }, { key: "status", label: "Status", render: (row) => <PerformanceStatus value={row.status} /> }, { key: "action", label: "Action", align: "right", render: (row) => row.status === "planned" ? <Button type="button" size="sm" variant="outline" disabled={checkinUpdate.isPending} onClick={() => checkinUpdate.mutate(row.id)}>Mark completed</Button> : <span className="text-muted-foreground">Recorded</span> }]} />}</CardContent></Card>
    <Card><CardHeader><CardTitle><h2>Improvement plans</h2></CardTitle><CardDescription>Documented expectations, support resources, success measures, cadence, and outcomes.</CardDescription></CardHeader><CardContent>{plans.isLoading ? <PerformanceLoading cards={2} /> : plans.error || !plans.data ? <PerformanceError error={plans.error} /> : <PerformanceTable<ImprovementPlan> caption="Performance improvement plans ordered newest first." rows={plans.data.data} getKey={(row) => row.id} columns={[{ key: "employee", label: "Employee", render: (row) => <div><span className="font-medium">{row.employee?.primary_name ?? `Employee ${row.employee_id}`}</span><p className="text-xs text-muted-foreground">{row.title}</p></div> }, { key: "period", label: "Support period", render: (row) => `${row.starts_on} – ${row.ends_on}` }, { key: "cadence", label: "Check-in", render: (row) => row.checkin_frequency }, { key: "status", label: "Status", render: (row) => <PerformanceStatus value={row.status} /> }, { key: "action", label: "Next action", align: "right", render: (row) => <PlanActions row={row} busy={planAction.isPending} onAction={(action) => planAction.mutate({ id: row.id, action })} /> }]} />}</CardContent></Card>
  </PerformanceShell>;
}

function FeedbackForm({ references, busy, onSubmit }: FormProps) { function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const feedback = values.get("feedback") || null; onSubmit({ subject_employee_id: Number(values.get("employee_id")), author_employee_id: Number(values.get("author_employee_id")) || null, relationship: values.get("relationship"), visibility: values.get("visibility"), status: feedback ? "submitted" : "requested", strengths: values.get("strengths") || null, feedback, growth_suggestion: values.get("growth") || null, due_on: values.get("due_on") || null, prompts: ["What should this person continue?", "What could increase their impact?"] }); } return <ActivityForm id="feedback-form" title="Request or record feedback" description="Leave feedback blank to send a request, or add feedback now to record a submitted response." busy={busy} button="Save feedback" onSubmit={submit}><EmployeeSelect references={references} id="feedback-subject" name="employee_id" label="Employee receiving feedback (required)" /><EmployeeSelect references={references} id="feedback-author" name="author_employee_id" label="Feedback author" required={false} /><div className="grid gap-4 md:grid-cols-3"><Select id="feedback-relationship" name="relationship" label="Relationship (required)" options={["manager", "peer", "direct_report", "customer", "self"]} /><Select id="feedback-visibility" name="visibility" label="Visibility (required)" options={["manager_and_subject", "manager_only", "subject_only"]} /><Field id="feedback-due" label="Response due"><Input id="feedback-due" name="due_on" type="date" /></Field></div><LongField id="feedback-strengths" name="strengths" label="Strengths" /><LongField id="feedback-response" name="feedback" label="Feedback response" /><LongField id="feedback-growth" name="growth" label="Growth suggestion" /></ActivityForm>; }
function CheckinForm({ references, busy, onSubmit }: FormProps) { function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); onSubmit({ employee_id: Number(values.get("employee_id")), manager_employee_id: Number(values.get("manager_employee_id")) || null, checkin_on: values.get("checkin_on"), progress_percent: values.get("progress_percent") === "" ? null : Number(values.get("progress_percent")), wins: values.get("wins") || null, blockers: values.get("blockers") || null, support_needed: values.get("support_needed") || null, next_steps: values.get("next_steps") || null, status: values.get("status") }); } return <ActivityForm id="checkin-form" title="Schedule or complete a check-in" description="Capture wins, blockers, manager support, next steps, and optional goal progress." busy={busy} button="Save check-in" onSubmit={submit}><div className="grid gap-4 md:grid-cols-2"><EmployeeSelect references={references} id="checkin-employee" name="employee_id" label="Employee (required)" /><EmployeeSelect references={references} id="checkin-manager" name="manager_employee_id" label="Manager" required={false} /></div><div className="grid gap-4 md:grid-cols-3"><Field id="checkin-date" label="Check-in date (required)"><Input id="checkin-date" name="checkin_on" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></Field><Field id="checkin-progress" label="Goal progress percent"><Input id="checkin-progress" name="progress_percent" type="number" min="0" max="100" step="0.1" /></Field><Select id="checkin-status" name="status" label="Status (required)" options={["planned", "completed", "missed", "cancelled"]} /></div><div className="grid gap-4 md:grid-cols-2"><LongField id="checkin-wins" name="wins" label="Wins" /><LongField id="checkin-blockers" name="blockers" label="Blockers" /><LongField id="checkin-support" name="support_needed" label="Support needed" /><LongField id="checkin-next" name="next_steps" label="Next steps" /></div></ActivityForm>; }
function PlanForm({ references, busy, onSubmit }: FormProps) { function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const lines = (name: string) => String(values.get(name) ?? "").split("\n").map((line) => line.trim()).filter(Boolean); onSubmit({ employee_id: Number(values.get("employee_id")), manager_employee_id: Number(values.get("manager_employee_id")) || null, title: values.get("title"), reason: values.get("reason"), objectives: lines("objectives"), support_resources: lines("resources"), success_measures: lines("measures"), starts_on: values.get("starts_on"), ends_on: values.get("ends_on"), checkin_frequency: values.get("frequency"), status: "draft" }); } return <ActivityForm id="improvement-plan-form" title="Create improvement plan" description="Use a defined support period, observable objectives, and measurable success criteria. This is a development control, not an automatic disciplinary outcome." busy={busy} button="Save draft plan" onSubmit={submit}><div className="grid gap-4 md:grid-cols-2"><EmployeeSelect references={references} id="plan-employee" name="employee_id" label="Employee (required)" /><EmployeeSelect references={references} id="plan-manager" name="manager_employee_id" label="Responsible manager" required={false} /></div><Field id="plan-title" label="Plan title (required)"><Input id="plan-title" name="title" required maxLength={220} /></Field><LongField id="plan-reason" name="reason" label="Reason and context (required)" required minLength={20} /><div className="grid gap-4 md:grid-cols-3"><LinesField id="plan-objectives" name="objectives" label="Objectives, one per line (required)" required /><LinesField id="plan-resources" name="resources" label="Support resources, one per line" /><LinesField id="plan-measures" name="measures" label="Success measures, one per line (required)" required /></div><div className="grid gap-4 md:grid-cols-3"><Field id="plan-start" label="Starts on (required)"><Input id="plan-start" name="starts_on" type="date" required /></Field><Field id="plan-end" label="Ends on (required)"><Input id="plan-end" name="ends_on" type="date" required /></Field><Select id="plan-frequency" name="frequency" label="Check-in frequency (required)" options={["weekly", "biweekly", "monthly"]} /></div></ActivityForm>; }

type FormProps = { references: PerformanceReferences; busy: boolean; onSubmit: (payload: Record<string, unknown>) => void };
function ActivityForm({ id, title, description, busy, button, onSubmit, children }: { id: string; title: string; description: string; busy: boolean; button: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void; children: React.ReactNode }) { return <Card id={id}><CardHeader><CardTitle><h2>{title}</h2></CardTitle><CardDescription>{description} Required fields are identified in each label.</CardDescription></CardHeader><CardContent><form className="grid gap-5" onSubmit={onSubmit}>{children}<Button type="submit" disabled={busy} className="w-fit"><Plus aria-hidden="true" data-icon="inline-start" /><BusyLabel busy={busy}>{button}</BusyLabel></Button></form></CardContent></Card>; }
function ActivityButton({ selected, controls, onClick, icon: Icon, children }: { selected: boolean; controls: string; onClick: () => void; icon: typeof MessageSquareText; children: React.ReactNode }) { return <Button type="button" variant={selected ? "default" : "outline"} aria-pressed={selected} aria-expanded={selected} aria-controls={controls} onClick={onClick}><Icon aria-hidden="true" data-icon="inline-start" />{children}</Button>; }
function EmployeeSelect({ references, id, name, label, required = true }: { references: PerformanceReferences; id: string; name: string; label: string; required?: boolean }) { return <Field id={id} label={label}><NativeSelect id={id} name={name} required={required} className="w-full" defaultValue={required ? references.current_employee_id ?? "" : ""}><NativeSelectOption value="">{required ? "Select employee" : "Not specified"}</NativeSelectOption>{references.employees.map((employee) => <NativeSelectOption key={employee.id} value={employee.id}>{employee.primary_name} ({employee.employee_number})</NativeSelectOption>)}</NativeSelect></Field>; }
function PlanActions({ row, busy, onAction }: { row: ImprovementPlan; busy: boolean; onAction: (action: "activate" | "acknowledge" | "successful" | "extend" | "unsuccessful" | "cancel") => void }) { if (["successful", "unsuccessful", "cancelled"].includes(row.status)) return <span className="text-muted-foreground">Closed</span>; return <><Label htmlFor={`plan-action-${row.id}`} className="sr-only">Action for {row.title}</Label><NativeSelect id={`plan-action-${row.id}`} defaultValue="" className="w-40" disabled={busy} onChange={(event) => { if (event.target.value) onAction(event.target.value as Parameters<typeof onAction>[0]); event.currentTarget.value = ""; }}><NativeSelectOption value="">Choose action</NativeSelectOption>{row.status === "draft" ? <NativeSelectOption value="activate">Activate</NativeSelectOption> : null}<NativeSelectOption value="acknowledge">Acknowledge</NativeSelectOption>{row.status === "active" || row.status === "extended" ? <><NativeSelectOption value="successful">Close successful</NativeSelectOption><NativeSelectOption value="extend">Extend</NativeSelectOption><NativeSelectOption value="unsuccessful">Close unsuccessful</NativeSelectOption></> : null}<NativeSelectOption value="cancel">Cancel</NativeSelectOption></NativeSelect></>; }
function Field({ id, label, children }: { id: string; label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label htmlFor={id}>{label}</Label>{children}</div>; }
function Select({ id, name, label, options }: { id: string; name: string; label: string; options: string[] }) { return <Field id={id} label={label}><NativeSelect id={id} name={name} required className="w-full" defaultValue={options[0]}>{options.map((option) => <NativeSelectOption key={option} value={option}>{option.replaceAll("_", " ")}</NativeSelectOption>)}</NativeSelect></Field>; }
function LongField({ id, name, label, required, minLength }: { id: string; name: string; label: string; required?: boolean; minLength?: number }) { return <Field id={id} label={label}><Textarea id={id} name={name} required={required} minLength={minLength} maxLength={12000} /></Field>; }
function LinesField({ id, name, label, required }: { id: string; name: string; label: string; required?: boolean }) { return <Field id={id} label={label}><Textarea id={id} name={name} required={required} aria-describedby={`${id}-help`} /><p id={`${id}-help`} className="text-xs text-muted-foreground">Each non-empty line becomes one item.</p></Field>; }

