"use client";

import { useState, type FormEvent } from "react";
import { CheckCircle2, ChevronRight, Scale, Send } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";
import { usePermissions } from "@/hooks/use-permissions";
import { performanceApi } from "@/modules/performance/api";
import type { Competency, PerformanceReview } from "@/modules/performance/types";
import { BusyLabel, PerformanceEmpty, PerformanceError, PerformanceLoading, PerformanceShell, PerformanceStatus, Score } from "@/modules/performance/pages/components/performance-shell";

type ReviewAction = "self-submit" | "manager-submit" | "calibrate" | "acknowledge";

export default function PerformanceReviewsPage() {
  const [selectedId, setSelectedId] = useState<number | null>(null); const client = useQueryClient();
  const { hasAnyPermission } = usePermissions();
  const canSelf = hasAnyPermission(["submit_self_reviews", "manage_performance"]); const canManage = hasAnyPermission(["conduct_performance_reviews", "manage_performance"]); const canCalibrate = hasAnyPermission(["calibrate_performance", "manage_performance"]); const canAcknowledge = hasAnyPermission(["acknowledge_performance_reviews", "manage_performance"]);
  const reviews = useQuery({ queryKey: ["performance", "reviews"], queryFn: () => performanceApi.reviews({ per_page: 100 }) });
  const references = useQuery({ queryKey: ["performance", "references"], queryFn: performanceApi.references });
  const detail = useQuery({ queryKey: ["performance", "review", selectedId], queryFn: () => performanceApi.review(selectedId!), enabled: selectedId !== null });
  const action = useMutation({ mutationFn: ({ id, action, payload }: { id: number; action: ReviewAction; payload: Record<string, unknown> }) => performanceApi.reviewAction(id, action, payload), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["performance"] }); toast.success("Performance review updated."); }, onError: () => toast.error("The review action could not be completed.") });
  return <PerformanceShell title="Employee and manager reviews" description="Employees reflect on outcomes and behaviors; managers evaluate evidence, calibration protects consistency, and employees acknowledge completed reviews.">
    <Alert><Scale aria-hidden="true" /><AlertTitle>Evidence-led and manager-accountable</AlertTitle><AlertDescription>Goal progress and competency ratings determine the configured score. Attendance snapshots can support context, but they never calculate or change an employee rating.</AlertDescription></Alert>
    {reviews.isLoading ? <PerformanceLoading /> : reviews.error || !reviews.data ? <PerformanceError error={reviews.error} /> : reviews.data.data.length === 0 ? <PerformanceEmpty title="No reviews yet" description="Activate a review cycle to create one review per active employee." /> : <div className="grid gap-4">{reviews.data.data.map((review) => <ReviewCard key={review.id} review={review} expanded={selectedId === review.id} onToggle={() => setSelectedId((current) => current === review.id ? null : review.id)} />)}</div>}
    {selectedId !== null ? <section id={`review-workspace-${selectedId}`} aria-labelledby="review-workspace-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="review-workspace-heading">Review workspace</h2></CardTitle><CardDescription>Complete the action available for this review stage. Required fields are identified in each label.</CardDescription></CardHeader><CardContent>{detail.isLoading || references.isLoading ? <PerformanceLoading cards={2} /> : detail.error || !detail.data ? <PerformanceError error={detail.error} title="Review details could not be loaded" /> : <ReviewWorkspace review={detail.data} competencies={references.data?.competencies ?? []} permissions={{ canSelf, canManage, canCalibrate, canAcknowledge }} busy={action.isPending} onAction={(next, payload) => action.mutate({ id: detail.data.id, action: next, payload })} />}</CardContent></Card></section> : null}
  </PerformanceShell>;
}

function ReviewCard({ review, expanded, onToggle }: { review: PerformanceReview; expanded: boolean; onToggle: () => void }) { return <Card><CardContent className="flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between"><div className="grid gap-1"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{review.employee?.primary_name ?? `Employee ${review.employee_id}`}</span><PerformanceStatus value={review.status} /></div><p className="text-sm text-muted-foreground">{review.cycle?.name ?? "Review cycle"} · Manager: {review.manager?.primary_name ?? "Unassigned"} · Due: {review.due_on ?? "Not set"}</p></div><div className="flex items-center gap-4"><div className="text-right"><p className="text-xs text-muted-foreground">Overall score</p><Score value={review.overall_score} /></div><Button type="button" variant="outline" aria-expanded={expanded} aria-controls={`review-workspace-${review.id}`} onClick={onToggle}>Work on review<ChevronRight aria-hidden="true" data-icon="inline-end" className={expanded ? "rotate-90 transition-transform" : "transition-transform"} /></Button></div></CardContent></Card>; }

function ReviewWorkspace({ review, competencies, permissions, busy, onAction }: { review: PerformanceReview; competencies: Competency[]; permissions: { canSelf: boolean; canManage: boolean; canCalibrate: boolean; canAcknowledge: boolean }; busy: boolean; onAction: (action: ReviewAction, payload: Record<string, unknown>) => void }) {
  const evidence = review.evidence_snapshot;
  return <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Employee" value={review.employee?.primary_name ?? `Employee ${review.employee_id}`} /><Summary label="Manager" value={review.manager?.primary_name ?? "Not assigned"} /><Summary label="Stage" value={<PerformanceStatus value={review.status} />} /><Summary label="Rating" value={review.rating_label ?? "Not rated"} /></div>
    {evidence ? <Alert><CheckCircle2 aria-hidden="true" /><AlertTitle>Attendance evidence snapshot</AlertTitle><AlertDescription>{describeEvidence(evidence)}</AlertDescription></Alert> : null}
    {permissions.canSelf && ["not_started", "self_review", "returned"].includes(review.status) ? <SelfReviewForm review={review} competencies={competencies} busy={busy} onSubmit={(payload) => onAction("self-submit", payload)} /> : null}
    {permissions.canManage && ["not_started", "manager_review", "returned"].includes(review.status) ? <ManagerReviewForm review={review} competencies={competencies} busy={busy} onSubmit={(payload) => onAction("manager-submit", payload)} /> : null}
    {permissions.canCalibrate && ["calibration", "manager_submitted"].includes(review.status) ? <CalibrationForm review={review} busy={busy} onSubmit={(payload) => onAction("calibrate", payload)} /> : null}
    {permissions.canAcknowledge && review.status === "completed" && !review.acknowledged_at ? <AcknowledgeForm busy={busy} onSubmit={(payload) => onAction("acknowledge", payload)} /> : null}
    {review.status === "completed" ? <Card><CardHeader><CardTitle><h3>Completed review summary</h3></CardTitle></CardHeader><CardContent className="grid gap-4"><Summary label="Goal score" value={<Score value={review.goal_score} />} /><Summary label="Competency score" value={<Score value={review.competency_score} />} /><Summary label="Overall score" value={<Score value={review.overall_score} />} /><p className="text-sm"><span className="font-semibold">Manager summary:</span> {review.manager_summary ?? "No summary recorded."}</p></CardContent></Card> : null}
  </div>;
}

function SelfReviewForm({ review, competencies, busy, onSubmit }: { review: PerformanceReview; competencies: Competency[]; busy: boolean; onSubmit: (payload: Record<string, unknown>) => void }) { return <ActionForm title="Submit self-review" description="Reflect on delivered outcomes, strengths, growth areas, and one competency." busy={busy} button="Submit self-review" icon="send" onSubmit={(values) => onSubmit({ self_summary: values.get("summary"), strengths: values.get("strengths") || null, development_areas: values.get("development") || null, career_aspirations: values.get("career") || null, scores: [scorePayload(values)] })}><LongField id={`self-summary-${review.id}`} name="summary" label="Self-review summary (required)" minLength={20} required /><LongField id={`self-strengths-${review.id}`} name="strengths" label="Strengths demonstrated" /><LongField id={`self-development-${review.id}`} name="development" label="Development areas" /><LongField id={`self-career-${review.id}`} name="career" label="Career aspirations" /><ScoreFields prefix={`self-${review.id}`} competencies={competencies} /></ActionForm>; }
function ManagerReviewForm({ review, competencies, busy, onSubmit }: { review: PerformanceReview; competencies: Competency[]; busy: boolean; onSubmit: (payload: Record<string, unknown>) => void }) { return <ActionForm title="Submit manager evaluation" description="Evaluate results and behaviors using documented evidence. The configured cycle weights calculate the overall score." busy={busy} button="Submit manager evaluation" icon="send" onSubmit={(values) => onSubmit({ manager_summary: values.get("summary"), strengths: values.get("strengths"), development_areas: values.get("development"), potential_rating: values.get("potential") || null, recommendation: values.get("recommendation") || null, scores: [scorePayload(values)] })}><LongField id={`manager-summary-${review.id}`} name="summary" label="Manager summary (required)" minLength={20} required /><div className="grid gap-4 md:grid-cols-2"><LongField id={`manager-strengths-${review.id}`} name="strengths" label="Demonstrated strengths (required)" required /><LongField id={`manager-development-${review.id}`} name="development" label="Development areas (required)" required /></div><div className="grid gap-4 md:grid-cols-2"><Select id={`manager-potential-${review.id}`} name="potential" label="Potential assessment" options={["", "low", "moderate", "high", "critical"]} /><Select id={`manager-recommendation-${review.id}`} name="recommendation" label="Recommendation" options={["", "retain", "develop", "promote", "reward", "improvement_plan", "role_change"]} /></div><ScoreFields prefix={`manager-${review.id}`} competencies={competencies} /></ActionForm>; }
function CalibrationForm({ review, busy, onSubmit }: { review: PerformanceReview; busy: boolean; onSubmit: (payload: Record<string, unknown>) => void }) { return <ActionForm title="Calibrate final result" description={`Manager result: ${Number(review.manager_score ?? 0).toFixed(1)}%. Record the calibrated score and rationale.`} busy={busy} button="Complete calibration" icon="scale" onSubmit={(values) => onSubmit({ calibrated_score: Number(values.get("score")), calibration_notes: values.get("notes") })}><Field id={`calibrated-score-${review.id}`} label="Calibrated score out of 100 (required)"><Input id={`calibrated-score-${review.id}`} name="score" type="number" min="0" max="100" step="0.1" defaultValue={Number(review.manager_score ?? 0)} required /></Field><LongField id={`calibration-notes-${review.id}`} name="notes" label="Calibration rationale (required)" minLength={10} required /></ActionForm>; }
function AcknowledgeForm({ busy, onSubmit }: { busy: boolean; onSubmit: (payload: Record<string, unknown>) => void }) { return <ActionForm title="Acknowledge completed review" description="Acknowledgement confirms the employee received the review; it does not necessarily indicate agreement." busy={busy} button="Acknowledge review" icon="check" onSubmit={(values) => onSubmit({ employee_comments: values.get("comments") || null })}><LongField id="review-acknowledgement-comments" name="comments" label="Employee comments" /></ActionForm>; }

function ActionForm({ title, description, busy, button, icon, onSubmit, children }: { title: string; description: string; busy: boolean; button: string; icon: "send" | "scale" | "check"; onSubmit: (values: FormData) => void; children: React.ReactNode }) { const Icon = icon === "scale" ? Scale : icon === "check" ? CheckCircle2 : Send; function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSubmit(new FormData(event.currentTarget)); } return <Card><CardHeader><CardTitle><h3>{title}</h3></CardTitle><CardDescription>{description} Required fields are identified in each label.</CardDescription></CardHeader><CardContent><form className="grid gap-5" onSubmit={submit}>{children}<Button type="submit" className="w-fit" disabled={busy}><Icon aria-hidden="true" data-icon="inline-start" /><BusyLabel busy={busy}>{button}</BusyLabel></Button></form></CardContent></Card>; }
function ScoreFields({ prefix, competencies }: { prefix: string; competencies: Competency[] }) { return <div className="grid gap-4 md:grid-cols-3"><Select id={`${prefix}-competency`} name="competency_id" label="Competency" options={["", ...competencies.map((item) => String(item.id))]} optionLabel={(value) => competencies.find((item) => String(item.id) === value)?.name ?? (value ? value : "General performance")} /><Field id={`${prefix}-score`} label="Score out of 5 (required)"><Input id={`${prefix}-score`} name="score" type="number" min="0" max="5" step="0.1" required /></Field><Field id={`${prefix}-evidence`} label="Rating evidence"><Input id={`${prefix}-evidence`} name="evidence" maxLength={4000} /></Field></div>; }
function scorePayload(values: FormData) { const competency = Number(values.get("competency_id")); return { competency_id: competency || null, score: Number(values.get("score")), evidence: values.get("evidence") || null }; }
function LongField({ id, name, label, required, minLength }: { id: string; name: string; label: string; required?: boolean; minLength?: number }) { return <Field id={id} label={label}><Textarea id={id} name={name} required={required} minLength={minLength} maxLength={12000} /></Field>; }
function Select({ id, name, label, options, optionLabel }: { id: string; name: string; label: string; options: string[]; optionLabel?: (value: string) => string }) { return <Field id={id} label={label}><NativeSelect id={id} name={name} className="w-full" defaultValue={options[0]}>{options.map((option) => <NativeSelectOption key={option || "empty"} value={option}>{optionLabel?.(option) ?? (option ? option.replaceAll("_", " ") : "Not specified")}</NativeSelectOption>)}</NativeSelect></Field>; }
function Field({ id, label, children }: { id: string; label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label htmlFor={id}>{label}</Label>{children}</div>; }
function Summary({ label, value }: { label: string; value: React.ReactNode }) { return <div className="rounded-xl border bg-muted/30 p-3"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><div className="mt-1 text-sm font-semibold">{value}</div></div>; }
function describeEvidence(evidence: Record<string, unknown>) { if (typeof evidence.reason === "string") return evidence.reason; const present = Number(evidence.present_days ?? 0); const late = Number(evidence.late_days ?? 0); const absent = Number(evidence.absent_days ?? 0); return `${present} present day(s), ${late} late day(s), and ${absent} absent day(s) in the review period.`; }

