"use client";

import { useState, type FormEvent } from "react";
import { Plus, Power } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";
import { performanceApi } from "@/modules/performance/api";
import type { Competency } from "@/modules/performance/types";
import { BusyLabel, PerformanceError, PerformanceLoading, PerformanceShell, PerformanceStatus, PerformanceTable } from "@/modules/performance/pages/components/performance-shell";

export default function PerformanceSettingsPage() { const [creating, setCreating] = useState(false); const client = useQueryClient(); const query = useQuery({ queryKey: ["performance", "competencies"], queryFn: () => performanceApi.competencies({ per_page: 100 }) }); const refresh = async () => { await client.invalidateQueries({ queryKey: ["performance"] }); }; const create = useMutation({ mutationFn: performanceApi.createCompetency, onSuccess: async () => { await refresh(); setCreating(false); toast.success("Competency created."); }, onError: () => toast.error("Competency could not be created.") }); const toggle = useMutation({ mutationFn: (item: Competency) => performanceApi.updateCompetency(item.id, { is_active: !item.is_active }), onSuccess: async () => { await refresh(); toast.success("Competency status updated."); }, onError: () => toast.error("Competency status could not be updated.") }); return <PerformanceShell title="Competency library and settings" description="Define observable behaviors used in self and manager reviews. Deactivate retired competencies to preserve historical scores." actions={<Button type="button" aria-expanded={creating} aria-controls="new-competency" onClick={() => setCreating((value) => !value)}><Plus aria-hidden="true" data-icon="inline-start" />{creating ? "Close competency form" : "New competency"}</Button>}>
  {creating ? <CompetencyForm id="new-competency" busy={create.isPending} onSubmit={(payload) => create.mutate(payload)} /> : null}
  <Card><CardHeader><CardTitle><h2>Competency library</h2></CardTitle><CardDescription>Core, leadership, functional, values, and technical behaviors available to performance reviews.</CardDescription></CardHeader><CardContent>{query.isLoading ? <PerformanceLoading cards={2} /> : query.error || !query.data ? <PerformanceError error={query.error} /> : <PerformanceTable<Competency> caption="Performance competency library ordered by configured sort order." rows={query.data.data} getKey={(row) => row.id} columns={[{ key: "code", label: "Code", render: (row) => <span className="font-mono font-medium">{row.code}</span> }, { key: "competency", label: "Competency", render: (row) => <div><span className="font-medium">{row.name}</span><p className="max-w-md text-xs text-muted-foreground">{row.description || "No description"}</p></div> }, { key: "category", label: "Category", render: (row) => <PerformanceStatus value={row.category} /> }, { key: "scale", label: "Scale", align: "right", render: (row) => `0–${Number(row.max_score)}` }, { key: "weight", label: "Default weight", align: "right", render: (row) => `${Number(row.default_weight)}%` }, { key: "status", label: "Status", render: (row) => <PerformanceStatus value={row.is_active ? "active" : "inactive"} /> }, { key: "action", label: "Action", align: "right", render: (row) => <Button type="button" size="sm" variant="outline" disabled={toggle.isPending} onClick={() => toggle.mutate(row)}><Power aria-hidden="true" data-icon="inline-start" />{row.is_active ? "Deactivate" : "Activate"}</Button> }]} />}</CardContent></Card>
  </PerformanceShell>; }

function CompetencyForm({ id, busy, onSubmit }: { id: string; busy: boolean; onSubmit: (payload: Record<string, unknown>) => void }) { function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const indicators = String(values.get("indicators") ?? "").split("\n").map((line) => line.trim()).filter(Boolean); onSubmit({ code: values.get("code"), name: values.get("name"), description: values.get("description") || null, category: values.get("category"), max_score: Number(values.get("max_score")), default_weight: Number(values.get("default_weight")), behavioral_indicators: indicators, is_active: true, sort_order: Number(values.get("sort_order") || 0) }); } return <Card id={id}><CardHeader><CardTitle><h2>Create competency</h2></CardTitle><CardDescription>Use observable and role-relevant behaviors. Required fields are identified in each label.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="grid gap-5"><div className="grid gap-4 md:grid-cols-3"><Field id="competency-code" label="Code (required)"><Input id="competency-code" name="code" required maxLength={80} /></Field><Field id="competency-name" label="Name (required)"><Input id="competency-name" name="name" required maxLength={180} /></Field><Field id="competency-category" label="Category (required)"><NativeSelect id="competency-category" name="category" required defaultValue="core" className="w-full">{["core", "leadership", "functional", "values", "technical"].map((item) => <NativeSelectOption key={item} value={item}>{item}</NativeSelectOption>)}</NativeSelect></Field></div><Field id="competency-description" label="Description"><Textarea id="competency-description" name="description" maxLength={4000} /></Field><div className="grid gap-4 md:grid-cols-3"><Field id="competency-scale" label="Maximum score (required)"><Input id="competency-scale" name="max_score" type="number" min="1" max="10" defaultValue="5" required /></Field><Field id="competency-weight" label="Default weight percent"><Input id="competency-weight" name="default_weight" type="number" min="0" max="100" step="0.1" defaultValue="0" /></Field><Field id="competency-order" label="Sort order"><Input id="competency-order" name="sort_order" type="number" min="0" max="10000" defaultValue="0" /></Field></div><Field id="competency-indicators" label="Behavioral indicators"><Textarea id="competency-indicators" name="indicators" aria-describedby="competency-indicators-help" /><p id="competency-indicators-help" className="text-xs text-muted-foreground">Enter one observable behavior per line.</p></Field><Button type="submit" className="w-fit" disabled={busy}><BusyLabel busy={busy}>Create competency</BusyLabel></Button></form></CardContent></Card>; }
function Field({ id, label, children }: { id: string; label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label htmlFor={id}>{label}</Label>{children}</div>; }

