"use client";

import Link from "next/link";
import { ArrowRight, UsersRound } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { performanceApi } from "@/modules/performance/api";
import type { PerformanceReview } from "@/modules/performance/types";
import { PerformanceCharts } from "@/modules/performance/pages/components/performance-charts";
import { MetricCard, PerformanceError, PerformanceLoading, PerformanceShell, PerformanceStatus, PerformanceTable, Score } from "@/modules/performance/pages/components/performance-shell";

export default function TeamPerformancePage() { const dashboard = useQuery({ queryKey: ["performance", "dashboard"], queryFn: performanceApi.dashboard }); const reviews = useQuery({ queryKey: ["performance", "reviews", "team"], queryFn: () => performanceApi.reviews({ per_page: 100 }) }); return <PerformanceShell title="Team performance" description="Give managers a responsible view of outcomes, review readiness, coaching rhythm, and development needs for their reporting scope." actions={<Button asChild><Link href="/dashboard/performance/reviews">Conduct reviews<ArrowRight aria-hidden="true" data-icon="inline-end" /></Link></Button>}>
  <Alert><UsersRound aria-hidden="true" /><AlertTitle>Scoped to authorized employees</AlertTitle><AlertDescription>People managers see their reporting tree; employees see themselves; performance administrators can view the organization. The API enforces the same boundary for every record.</AlertDescription></Alert>
  {dashboard.isLoading ? <PerformanceLoading /> : dashboard.error || !dashboard.data ? <PerformanceError error={dashboard.error} /> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard title="Team completion" value={`${dashboard.data.metrics.completion_rate.toFixed(1)}%`} description="Completed reviews within the visible team scope." /><MetricCard title="Team average" value={<Score value={dashboard.data.metrics.average_score} />} description="Completed review average; use calibration before comparisons." /><MetricCard title="Goals at risk" value={dashboard.data.metrics.goals_at_risk} description="Blocked or at-risk employee commitments." status={dashboard.data.metrics.goals_at_risk ? "at_risk" : "clear"} /><MetricCard title="Overdue reviews" value={dashboard.data.metrics.reviews_overdue} description="Manager or employee action is late." status={dashboard.data.metrics.reviews_overdue ? "overdue" : "clear"} /></div><PerformanceCharts data={dashboard.data} /></>}
  <Card><CardHeader><CardTitle><h2>Team review register</h2></CardTitle><CardDescription>Review status, ownership, due date, and current outcome for every employee in scope.</CardDescription></CardHeader><CardContent>{reviews.isLoading ? <PerformanceLoading cards={2} /> : reviews.error || !reviews.data ? <PerformanceError error={reviews.error} /> : <PerformanceTable<PerformanceReview> caption="Team performance reviews ordered by due date." rows={reviews.data.data} getKey={(row) => row.id} columns={[{ key: "employee", label: "Employee", render: (row) => <div><span className="font-medium">{row.employee?.primary_name ?? `Employee ${row.employee_id}`}</span><p className="text-xs text-muted-foreground">{row.employee?.employee_number}</p></div> }, { key: "manager", label: "Manager", render: (row) => row.manager?.primary_name ?? "Unassigned" }, { key: "cycle", label: "Cycle", render: (row) => row.cycle?.name ?? "—" }, { key: "due", label: "Due", render: (row) => row.due_on ?? "Not set" }, { key: "status", label: "Status", render: (row) => <PerformanceStatus value={row.status} /> }, { key: "score", label: "Score", align: "right", render: (row) => <Score value={row.overall_score} /> }]} />}</CardContent></Card>
  </PerformanceShell>; }

