import { LayoutDashboard, Sofa, CalendarCheck2, ReceiptText, Utensils, Map as MapIcon, Users, MessageSquare, CreditCard, GalleryHorizontalEnd, Tag as TagIcon } from "lucide-react";
import type { FrontendModuleDefinition } from "@/modules/types";

export const hospitalityModule: FrontendModuleDefinition = {
  id: "hospitality",
  name: "Hospitality",
  description: "Restaurant, lounge, bar, club, and venue operations covering tables, reservations, service orders, menu, events, and staff.",
  backendModule: "Modules\\Hospitality",
  routePrefixes: [
    "/dashboard/hospitality",
    "/dashboard/hospitality/tables",
    "/dashboard/hospitality/reservations",
    "/dashboard/hospitality/service-orders",
    "/dashboard/hospitality/space",
    "/dashboard/hospitality/door",
    "/dashboard/hospitality/menu",
    "/dashboard/hospitality/menu-categories",
    "/dashboard/hospitality/zones",
    "/dashboard/hospitality/staff",
    "/dashboard/hospitality/crm",
    "/dashboard/hospitality/events",
    "/dashboard/hospitality/feedback",
    "/dashboard/hospitality/checkout",
    "/dashboard/hospitality/hero-slider",
  ],
  navItems: [
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality",
      fallbackLabel: "Hospitality Overview",
      href: "/dashboard/hospitality",
      icon: LayoutDashboard,
      subscriptionSlug: "hospitality",
      tourId: "tour-nav-hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_space",
      fallbackLabel: "Space Management",
      href: "/dashboard/hospitality/space",
      icon: MapIcon,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_zones",
      fallbackLabel: "Zones",
      href: "/dashboard/hospitality/zones",
      icon: MapIcon,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_door",
      fallbackLabel: "Door & Guest List",
      href: "/dashboard/hospitality/door",
      icon: Users,
      subscriptionSlug: "hospitality",
      businessTypes: ["nightclub"],
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_tables",
      fallbackLabel: "Tables & Layout",
      href: "/dashboard/hospitality/tables",
      icon: Sofa,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_reservations",
      fallbackLabel: "Reservations",
      href: "/dashboard/hospitality/reservations",
      icon: CalendarCheck2,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_orders",
      fallbackLabel: "Service Orders",
      href: "/dashboard/hospitality/service-orders",
      icon: ReceiptText,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_menu",
      fallbackLabel: "Menu Management",
      href: "/dashboard/hospitality/menu",
      icon: Utensils,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_menu_categories",
      fallbackLabel: "Menu Categories",
      href: "/dashboard/hospitality/menu-categories",
      icon: TagIcon,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_staff",
      fallbackLabel: "Staff Shifts",
      href: "/dashboard/hospitality/staff",
      icon: Users,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_crm",
      fallbackLabel: "CRM & Customers",
      href: "/dashboard/hospitality/crm",
      icon: Users,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_events",
      fallbackLabel: "Events",
      href: "/dashboard/hospitality/events",
      icon: CalendarCheck2,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_feedback",
      fallbackLabel: "Feedback & Reviews",
      href: "/dashboard/hospitality/feedback",
      icon: MessageSquare,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_checkout",
      fallbackLabel: "POS & Checkout",
      href: "/dashboard/hospitality/checkout",
      icon: CreditCard,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
    {
      moduleId: "hospitality",
      translationKey: "nav.hospitality_hero_slider",
      fallbackLabel: "Hero Slider",
      href: "/dashboard/hospitality/hero-slider",
      icon: GalleryHorizontalEnd,
      subscriptionSlug: "hospitality",
      placement: "primary",
    },
  ],
};

