import { Factory, ClipboardList, Gauge, Droplets, ScrollText, Boxes, Recycle } from "lucide-react";
import type { FrontendModuleDefinition } from "@/modules/types";

export const productionModule: FrontendModuleDefinition = {
  id: "production",
  name: "Production",
  description:
    "Manufacturing execution for bottling plants: lines, bills of materials, work orders with lot codes, shift output, downtime and OEE, water treatment and CIP records, and batch traceability.",
  backendModule: "Modules\\Production",
  routePrefixes: [
    "/dashboard/production",
    "/dashboard/production/orders",
    "/dashboard/production/runs",
    "/dashboard/production/boms",
    "/dashboard/production/lines",
    "/dashboard/production/quality",
    "/dashboard/production/containers",
    "/dashboard/production/traceability",
  ],
  navItems: [
    {
      moduleId: "production",
      translationKey: "nav.production_overview",
      fallbackLabel: "Production",
      href: "/dashboard/production",
      icon: Gauge,
      permissions: ["view_production", "manage_production"],
      subscriptionSlug: "production_management",
      placement: "primary",
    },
    {
      moduleId: "production",
      translationKey: "nav.production_orders",
      fallbackLabel: "Work Orders",
      href: "/dashboard/production/orders",
      icon: ClipboardList,
      permissions: ["view_production", "manage_production", "manage_production_orders"],
      subscriptionSlug: "production_management",
      placement: "primary",
    },
    {
      moduleId: "production",
      translationKey: "nav.production_runs",
      fallbackLabel: "Shift Runs",
      href: "/dashboard/production/runs",
      icon: Factory,
      permissions: ["view_production", "manage_production", "record_production_runs"],
      subscriptionSlug: "production_management",
      placement: "primary",
    },
    {
      moduleId: "production",
      translationKey: "nav.production_quality",
      fallbackLabel: "Water & CIP",
      href: "/dashboard/production/quality",
      icon: Droplets,
      permissions: ["view_production", "manage_production", "record_water_treatment"],
      subscriptionSlug: "production_management",
      placement: "primary",
    },
    {
      moduleId: "production",
      translationKey: "nav.production_containers",
      fallbackLabel: "Jars & Deposits",
      href: "/dashboard/production/containers",
      icon: Recycle,
      permissions: [
        "view_container_deposits",
        "record_container_movements",
        "view_production",
        "manage_production",
      ],
      subscriptionSlug: "production_management",
      placement: "primary",
    },
    {
      moduleId: "production",
      translationKey: "nav.production_traceability",
      fallbackLabel: "Batch Trace",
      href: "/dashboard/production/traceability",
      icon: ScrollText,
      permissions: ["view_production_traceability", "view_production", "manage_production"],
      subscriptionSlug: "production_management",
      placement: "primary",
    },
    {
      moduleId: "production",
      translationKey: "nav.production_boms",
      fallbackLabel: "Bills of Materials",
      href: "/dashboard/production/boms",
      icon: Boxes,
      permissions: ["view_production", "manage_production", "manage_bom", "manage_production_boms"],
      subscriptionSlug: "production_management",
      placement: "secondary",
    },
    {
      moduleId: "production",
      translationKey: "nav.production_lines",
      fallbackLabel: "Production Lines",
      href: "/dashboard/production/lines",
      icon: Factory,
      permissions: ["view_production", "manage_production", "manage_production_lines"],
      subscriptionSlug: "production_management",
      placement: "secondary",
    },
  ],
};
