"use client";

import * as React from "react";
import { Box, ExternalLink, Loader2, RotateCcw } from "lucide-react";

import { Button } from "@/components/ui/button";
import { getAuthHeaders } from "@/lib/runtime-context";
import { cn } from "@/lib/utils";
import { isProtectedTenantFileUrl, openSecureAssetInNewTab } from "@/components/ui/secure-asset-image";

const MODEL_VIEWER_SCRIPT_SRC =
  "https://ajax.googleapis.com/ajax/libs/model-viewer/4.0.0/model-viewer.min.js";

let modelViewerLoaderPromise: Promise<void> | null = null;

const ensureModelViewerLoaded = () => {
  if (typeof window === "undefined") {
    return Promise.resolve();
  }

  if (customElements.get("model-viewer")) {
    return Promise.resolve();
  }

  if (modelViewerLoaderPromise) {
    return modelViewerLoaderPromise;
  }

  modelViewerLoaderPromise = new Promise<void>((resolve, reject) => {
    const existingScript = document.querySelector<HTMLScriptElement>(
      'script[data-model-viewer-loader="true"]'
    );

    if (existingScript) {
      existingScript.addEventListener("load", () => resolve(), { once: true });
      existingScript.addEventListener(
        "error",
        () => reject(new Error("Failed to load the 3D viewer runtime.")),
        { once: true }
      );
      return;
    }

    const script = document.createElement("script");
    script.type = "module";
    script.src = MODEL_VIEWER_SCRIPT_SRC;
    script.dataset.modelViewerLoader = "true";
    script.onload = () => resolve();
    script.onerror = () => reject(new Error("Failed to load the 3D viewer runtime."));
    document.head.appendChild(script);
  });

  return modelViewerLoaderPromise;
};

type Model3DViewerProps = {
  src: string | null | undefined;
  alt?: string;
  className?: string;
  viewerClassName?: string;
  emptyTitle?: string;
  emptyDescription?: string;
  errorTitle?: string;
  openButtonLabel?: string;
  showOpenButton?: boolean;
  autoRotate?: boolean;
  fallbackImage?: string;
};

export function Model3DViewer({
  src,
  alt = "3D model preview",
  className,
  viewerClassName,
  emptyTitle = "No 3D model available",
  emptyDescription = "Attach a GLB or GLTF file to preview it here.",
  errorTitle = "Could not load the 3D model preview",
  openButtonLabel = "Open Model",
  showOpenButton = true,
  autoRotate = true,
  fallbackImage,
}: Model3DViewerProps) {
  const [resolvedSrc, setResolvedSrc] = React.useState<string | null>(null);
  const [isPreparingSource, setIsPreparingSource] = React.useState(false);
  const [isViewerReady, setIsViewerReady] = React.useState(false);
  const [viewerError, setViewerError] = React.useState<string | null>(null);

  React.useEffect(() => {
    let isMounted = true;

    // WebGL capability check to prevent mounting model-viewer when drivers are exhausted/missing
    const hasWebGL = (() => {
      if (typeof window === "undefined") return false;
      try {
        const canvas = document.createElement("canvas");
        return !!(
          window.WebGLRenderingContext &&
          (canvas.getContext("webgl") || canvas.getContext("experimental-webgl"))
        );
      } catch (e) {
        return false;
      }
    })();

    if (!hasWebGL) {
      if (isMounted) {
        setViewerError("WebGL is not supported or enabled in this browser.");
      }
      return;
    }

    ensureModelViewerLoaded()
      .then(() => {
        if (isMounted) {
          setIsViewerReady(true);
        }
      })
      .catch((error) => {
        if (isMounted) {
          setViewerError(error instanceof Error ? error.message : "Failed to load 3D viewer.");
        }
      });

    return () => {
      isMounted = false;
    };
  }, []);

  React.useEffect(() => {
    if (!src) {
      setResolvedSrc(null);
      setViewerError(null);
      setIsPreparingSource(false);
      return;
    }

    if (!isProtectedTenantFileUrl(src)) {
      setResolvedSrc(src);
      setViewerError(null);
      setIsPreparingSource(false);
      return;
    }

    let isMounted = true;
    let objectUrl: string | null = null;

    setIsPreparingSource(true);
    setViewerError(null);

    (async () => {
      try {
        // 🚀 We don't send Authorization or X-Tenant headers here because the src URL 
        // generated by getStreamUrl already contains the necessary token, tenant and signature 
        // as query parameters. Sending them in headers can conflict with the backend's 
        // InitializeTenantContext middleware which expects signed headers for cross-domain requests.
        const response = await fetch(src);
        if (!response.ok) {
          throw new Error("Failed to fetch secure 3D asset.");
        }

        const blob = await response.blob();
        objectUrl = URL.createObjectURL(blob);

        if (isMounted) {
          setResolvedSrc(objectUrl);
        }
      } catch (error) {
        if (isMounted) {
          setResolvedSrc(null);
          setViewerError(error instanceof Error ? error.message : "Failed to load 3D model.");
        }
      } finally {
        if (isMounted) {
          setIsPreparingSource(false);
        }
      }
    })();

    return () => {
      isMounted = false;
      if (objectUrl) {
        URL.revokeObjectURL(objectUrl);
      }
    };
  }, [src]);

  const handleOpen = async () => {
    if (!src) return;
    await openSecureAssetInNewTab(src);
  };

  const frameClasses = cn(
    "relative overflow-hidden rounded-2xl border border-border/60 bg-[radial-gradient(circle_at_top,_rgba(59,130,246,0.16),_transparent_55%),linear-gradient(180deg,rgba(15,23,42,0.08),rgba(15,23,42,0.02))]",
    className
  );

  const bodyClasses = cn("h-full min-h-[280px] w-full", viewerClassName);

  if (!src) {
    return (
      <div className={frameClasses}>
        <div className="flex h-full min-h-[280px] flex-col items-center justify-center gap-4 p-6 text-center">
          <div className="rounded-2xl bg-primary/10 p-4">
            <Box className="h-10 w-10 text-primary" />
          </div>
          <div className="space-y-1">
            <p className="text-sm font-bold text-foreground">{emptyTitle}</p>
            <p className="max-w-sm text-xs text-muted-foreground">{emptyDescription}</p>
          </div>
        </div>
      </div>
    );
  }

  if (viewerError) {
    if (fallbackImage) {
      return (
        <div className={frameClasses}>
          <div className="relative w-full h-full min-h-[280px]">
            { }
            <img
              src={fallbackImage}
              alt={alt}
              className="w-full h-full object-cover"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent pointer-events-none" />
          </div>
        </div>
      );
    }

    return (
      <div className={frameClasses}>
        <div className="flex h-full min-h-[280px] flex-col items-center justify-center gap-4 p-6 text-center">
          <div className="rounded-2xl bg-destructive/10 p-4">
            <RotateCcw className="h-10 w-10 text-destructive" />
          </div>
          <div className="space-y-1">
            <p className="text-sm font-bold text-foreground">{errorTitle}</p>
            <p className="max-w-sm text-xs text-muted-foreground">{viewerError}</p>
          </div>
          {showOpenButton ? (
            <Button
              type="button"
              variant="outline"
              className="rounded-xl"
              onClick={() => {
                void handleOpen();
              }}
            >
              <ExternalLink className="mr-2 h-4 w-4" />
              {openButtonLabel}
            </Button>
          ) : null}
        </div>
      </div>
    );
  }

  if (!isViewerReady || isPreparingSource || !resolvedSrc) {
    return (
      <div className={frameClasses}>
        <div className="flex h-full min-h-[280px] flex-col items-center justify-center gap-4 p-6 text-center">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
          <div className="space-y-1">
            <p className="text-sm font-bold text-foreground">Preparing 3D preview</p>
            <p className="text-xs text-muted-foreground">Loading the model viewer and asset...</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={frameClasses}>
      {React.createElement("model-viewer", {
        src: resolvedSrc,
        alt,
        className: bodyClasses,
        style: { width: "100%", height: "100%" },
        exposure: "1",
        "shadow-intensity": "1",
        "camera-controls": true,
        "interaction-prompt": "auto",
        "touch-action": "pan-y",
        "auto-rotate": autoRotate,
      })}
      {showOpenButton ? (
        <div className="pointer-events-none absolute inset-x-0 bottom-0 flex justify-end bg-gradient-to-t from-background/90 via-background/40 to-transparent p-4">
          <Button
            type="button"
            variant="outline"
            className="pointer-events-auto rounded-xl bg-background/85"
            onClick={() => {
              void handleOpen();
            }}
          >
            <ExternalLink className="mr-2 h-4 w-4" />
            {openButtonLabel}
          </Button>
        </div>
      ) : null}
    </div>
  );
}
