"use client";
import { use, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CodeEditor, type VirtualFile } from "@/components/ui/code-editor";
import { getBackendApiRoot, getTenantHeaders } from "@/lib/runtime-context";
type Question={id:number;type:string;prompt:string;options?:string[];coding_config?:{language?:string;starter_code?:string;filename?:string};points:number};
type Payload={candidate_name:string;job_title:string;assessment:{title:string;instructions?:string;duration_minutes:number;require_fullscreen:boolean;integrity_monitoring_enabled:boolean};questions:Question[];attempt?:{started_at:string;expires_at:string;submitted_at?:string;status:string}};
export default function AssessmentPage({params}:{params:Promise<{token:string}>}){
 const{token}=use(params);const[data,setData]=useState<Payload|null>(null),[answers,setAnswers]=useState<Record<number,unknown>>({}),[consent,setConsent]=useState(false),[error,setError]=useState(""),[status,setStatus]=useState(""),[remaining,setRemaining]=useState(0);
 const base=getBackendApiRoot()+"/public/recruitment/assessments/"+token,headers={"Content-Type":"application/json",Accept:"application/json",...getTenantHeaders({allowUnsigned:true})};
 async function load(){const r=await fetch(base,{headers});const p=await r.json();if(!r.ok)throw new Error(p.message);setData(p.data);if(p.data.attempt?.expires_at)setRemaining(Math.max(0,Math.floor((new Date(p.data.attempt.expires_at).getTime()-Date.now())/1000)))}
 useEffect(()=>{load().catch(e=>setError(e.message||"This assessment could not be loaded."))},[token]);
 const started=Boolean(data?.attempt?.started_at&&!data?.attempt?.submitted_at);
 async function post(path:string,body?:unknown,method="POST"){const r=await fetch(base+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.message||"Request failed.");return p}
 async function record(event_type:string,metadata?:object){if(!started||!data?.assessment.integrity_monitoring_enabled)return;try{await post("/integrity-events",{event_type,metadata,occurred_at:new Date().toISOString()})}catch{}}
 useEffect(()=>{if(!started)return;const visibility=()=>{if(document.hidden)record("focus_lost")};const fullscreen=()=>{if(data?.assessment.require_fullscreen&&!document.fullscreenElement)record("fullscreen_exit")};const offline=()=>record("network_disconnect");document.addEventListener("visibilitychange",visibility);document.addEventListener("fullscreenchange",fullscreen);window.addEventListener("offline",offline);return()=>{document.removeEventListener("visibilitychange",visibility);document.removeEventListener("fullscreenchange",fullscreen);window.removeEventListener("offline",offline)}},[started,data?.assessment.require_fullscreen]);
 useEffect(()=>{if(!started)return;const timer=window.setInterval(()=>setRemaining(v=>Math.max(0,v-1)),1000);return()=>window.clearInterval(timer)},[started]);
 async function start(){try{if(data?.assessment.require_fullscreen)await document.documentElement.requestFullscreen();await post("/start");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to start.")}}
 async function save(question_id:number,answer:unknown){setAnswers(v=>({...v,[question_id]:answer}));try{await post("/answer",{question_id,answer},"PUT");setStatus("Answer saved.")}catch(e){setError(e instanceof Error?e.message:"Answer was not saved.")}}
 async function submit(){try{await post("/submit");setStatus("Assessment submitted successfully. You may close this page.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to submit assessment.")}}
 if(!data)return <main className="grid min-h-screen place-items-center bg-slate-950 p-6 text-slate-100"><p role={error?"alert":undefined}>{error||"Loading assessment…"}</p></main>;
 return <main className="min-h-screen bg-slate-950 text-slate-100"><header className="sticky top-0 z-20 border-b border-slate-500 bg-slate-950/95 px-4 py-4 backdrop-blur"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-300">{data.job_title}</p><h1 className="text-xl font-black">{data.assessment.title}</h1></div>{started&&<p className="flex min-h-11 items-center gap-2 rounded-full border border-slate-600 px-4 font-mono"><Clock3 aria-hidden className="h-4 w-4"/>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,"0")}</p>}</div></header>
 <div className="mx-auto max-w-6xl px-4 py-8">{error&&<p role="alert" className="mb-5 rounded-xl border border-red-400 bg-red-950 p-4">{error}</p>}{status&&<p role="status" className="mb-5 rounded-xl border border-emerald-400 bg-emerald-950 p-4">{status}</p>}
 {!started&&!data.attempt?.submitted_at?<section className="mx-auto max-w-2xl rounded-3xl border border-slate-500 bg-slate-900 p-8"><ShieldCheck aria-hidden className="h-10 w-10 text-emerald-300"/><h2 className="mt-5 text-3xl font-black">Before you begin</h2><p className="mt-3 text-slate-300">Hello {data.candidate_name}. You have {data.assessment.duration_minutes} minutes. {data.assessment.instructions}</p><div className="mt-6 rounded-xl border border-amber-500/60 bg-amber-950/40 p-4 text-sm"><p className="flex font-bold text-amber-200"><AlertTriangle aria-hidden className="mr-2 h-5 w-5"/>Integrity monitoring notice</p><p className="mt-2 text-amber-100">If enabled, Hive records focus loss, paste/copy, fullscreen exits, and network disconnects. It compares answer similarity inside this tenant. These signals require human review and never automatically reject you. Camera and microphone are not used.</p></div><label className="mt-6 flex gap-3"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 h-5 w-5"/><span>I understand the assessment rules and integrity monitoring described above.</span></label><Button type="button" disabled={!consent} onClick={start} className="mt-6 min-h-11 bg-emerald-700 hover:bg-emerald-800">Start assessment</Button></section>:
 data.attempt?.submitted_at?<section className="mx-auto max-w-2xl rounded-3xl border border-emerald-600 bg-emerald-950/30 p-8 text-center"><CheckCircle2 aria-hidden className="mx-auto h-12 w-12 text-emerald-300"/><h2 className="mt-4 text-3xl font-black">Assessment submitted</h2><p className="mt-3 text-slate-300">The recruitment committee will review your responses.</p></section>:
 <form onSubmit={e=>{e.preventDefault();submit()}} className="space-y-6">{data.questions.map((q,index)=><QuestionCard key={q.id} question={q} index={index} value={answers[q.id]} onSave={value=>save(q.id,value)} onIntegrity={record}/>)}<div className="sticky bottom-4 flex justify-end"><Button type="submit" className="min-h-12 bg-emerald-600 px-8 hover:bg-emerald-700">Submit final assessment</Button></div></form>}
 </div></main>
}
function QuestionCard({question,index,value,onSave,onIntegrity}:{question:Question;index:number;value:unknown;onSave:(v:unknown)=>void;onIntegrity:(type:string,metadata?:object)=>void}){
 const initial=useMemo<VirtualFile[]>(()=>[{name:question.coding_config?.filename||"solution.ts",language:question.coding_config?.language||"typescript",content:question.coding_config?.starter_code||""}],[question.id]);
 const[files,setFiles]=useState(initial);useEffect(()=>{if(question.type==="coding")onSave({files})},[files]);
 return <fieldset className="rounded-2xl border border-slate-500 bg-slate-900 p-5 sm:p-7"><legend className="px-2 text-sm font-bold text-emerald-300">Question {index+1} · {question.points} points</legend><p className="mt-2 whitespace-pre-wrap text-lg font-semibold">{question.prompt}</p><div className="mt-5" onPaste={()=>onIntegrity("paste",{question_id:question.id})} onCopy={()=>onIntegrity("copy",{question_id:question.id})}>
  {question.type==="single_choice"||question.type==="true_false"?<div className="space-y-3">{(question.options||(question.type==="true_false"?["True","False"]:[])).map(option=><label key={option} className="flex min-h-11 items-center gap-3 rounded-lg border border-slate-600 p-3"><input type="radio" name={"q-"+question.id} value={option} checked={value===option} onChange={()=>onSave(option)}/>{option}</label>)}</div>:
  question.type==="multiple_choice"?<div className="space-y-3">{(question.options||[]).map(option=><label key={option} className="flex min-h-11 items-center gap-3 rounded-lg border border-slate-600 p-3"><input type="checkbox" checked={Array.isArray(value)&&value.includes(option)} onChange={e=>{const current=Array.isArray(value)?value as string[]:[];onSave(e.target.checked?[...current,option]:current.filter(v=>v!==option))}}/>{option}</label>)}</div>:
  question.type==="coding"?<CodeEditor files={files} setFiles={setFiles} className="min-h-[28rem]"/>:
  <textarea aria-label={"Answer to question "+(index+1)} rows={question.type==="long_text"?10:4} value={String(value||"")} onChange={e=>onSave(e.target.value)} className="w-full rounded-lg border border-slate-500 bg-slate-950 p-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-300"/>}
 </div></fieldset>
}
