"use client";

import { useState, type FormEvent } from "react";
import { Ban, Check, Download, Plus, Send, Trash2, WalletCards } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Field, FieldDescription, FieldGroup, FieldLabel, FieldLegend, FieldSet } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { usePermissions } from "@/hooks/use-permissions";
import api from "@/modules/shared/api/http";
import { financeApi } from "@/modules/finance/api";
import type { FinanceAccount, FinanceContact, FinanceDocument } from "@/modules/finance/types";
import { BusyLabel, FinanceError, FinanceLoading, FinanceShell, FinanceStatus, FinanceTable, Money } from "@/modules/finance/pages/components/finance-shell";

const types = {
  sales: [["sales_quote", "Sales quote"], ["sales_order", "Sales order"], ["sales_invoice", "Sales invoice"], ["customer_receipt", "Customer receipt"], ["credit_note", "Credit note"]],
  purchases: [["purchase_order", "Purchase order"], ["purchase_bill", "Purchase bill"], ["vendor_payment", "Vendor payment"], ["expense", "Expense"], ["debit_note", "Debit note"]],
} as const;

export default function FinanceDocumentsPage({ group }: { group: "sales" | "purchases" }) {
  const [open, setOpen] = useState(false);
  const [paying, setPaying] = useState<FinanceDocument | null>(null);
  const client = useQueryClient();
  const { hasAnyPermission } = usePermissions();
  const canManage = hasAnyPermission(["manage_finance", group === "sales" ? "manage_sales" : "manage_purchases"]);
  const canApprove = hasAnyPermission(["manage_finance", group === "sales" ? "approve_sales" : "approve_purchases"]);
  const canPay = hasAnyPermission(["manage_finance", "record_finance_payments"]);
  const query = useQuery({ queryKey: ["finance", "documents", group], queryFn: () => financeApi.documents({ group, per_page: 100 }) });
  const contacts = useQuery({ queryKey: ["finance", "document-contacts", group], queryFn: () => financeApi.contacts({ type: group === "sales" ? "customer" : "vendor", active: true, per_page: 200 }) });
  const accounts = useQuery({ queryKey: ["finance", "document-accounts"], queryFn: () => financeApi.accounts({ active: true, per_page: 200 }) });
  const create = useMutation({ mutationFn: financeApi.createDocument, onSuccess: async () => { await client.invalidateQueries({ queryKey: ["finance"] }); setOpen(false); toast.success("Financial document created."); }, onError: () => toast.error("The document could not be created. Review each required line.") });
  const action = useMutation({ mutationFn: ({ document, action, payload = {} }: { document: FinanceDocument; action: "approve" | "post" | "pay" | "void"; payload?: Record<string, unknown> }) => financeApi.documentAction(document.id, action, payload), onSuccess: async (_, variables) => { await client.invalidateQueries({ queryKey: ["finance"] }); setPaying(null); toast.success(`Document ${variables.action === "pay" ? "payment recorded" : `${variables.action}ed`}.`); }, onError: () => toast.error("The document action could not be completed.") });

  async function download(document: FinanceDocument) {
    try { const response = await api.get(`/finance/documents/${document.id}/pdf`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = `${document.number}.pdf`; anchor.click(); URL.revokeObjectURL(url); }
    catch { toast.error("The PDF could not be downloaded."); }
  }

  const title = group === "sales" ? "Sales and receivables" : "Purchases and payables";
  const description = group === "sales" ? "Move quotes and orders into tax-ready invoices, receipts, credit notes, and receivable settlements." : "Control purchase orders, supplier bills, expenses, debit notes, and payable settlements.";
  return <FinanceShell title={title} description={description} actions={canManage ? <DocumentDialog group={group} open={open} onOpenChange={setOpen} contacts={contacts.data?.data ?? []} accounts={accounts.data?.data ?? []} busy={create.isPending} onSubmit={(payload) => create.mutate(payload)} /> : undefined}>
    <Card><CardHeader><CardTitle>{group === "sales" ? "Sales document register" : "Purchase document register"}</CardTitle></CardHeader><CardContent>
      {query.isLoading ? <FinanceLoading cards={2} /> : query.error || !query.data ? <FinanceError error={query.error} /> : <FinanceTable<FinanceDocument> caption={`${title} documents, newest first.`} rows={query.data.data} getKey={(row) => row.id} columns={[
        { key: "number", label: "Document", render: (row) => <div className="flex flex-col gap-1"><span className="font-mono font-medium">{row.number}</span><span className="text-xs text-muted-foreground">{row.type.replaceAll("_", " ")}</span></div> },
        { key: "contact", label: group === "sales" ? "Customer" : "Vendor", render: (row) => row.contact?.name || "Not assigned" },
        { key: "date", label: "Date", render: (row) => row.document_date },
        { key: "total", label: "Total", align: "right", render: (row) => <Money value={row.total} currency={row.currency} /> },
        { key: "balance", label: "Balance", align: "right", render: (row) => <Money value={Number(row.total) - Number(row.paid_amount)} currency={row.currency} /> },
        { key: "status", label: "Status", render: (row) => <FinanceStatus value={row.status} /> },
        { key: "actions", label: "Actions", align: "right", render: (row) => <div className="flex justify-end gap-1">{row.status === "draft" && canApprove ? <Button size="sm" onClick={() => action.mutate({ document: row, action: "approve" })}><Check data-icon="inline-start" aria-hidden="true" />Approve</Button> : null}{row.status === "approved" && canApprove ? <Button size="sm" onClick={() => action.mutate({ document: row, action: "post" })}><Send data-icon="inline-start" aria-hidden="true" />Post</Button> : null}{["posted", "partially_paid"].includes(row.status) && canPay && ["sales_invoice", "purchase_bill"].includes(row.type) ? <Button size="sm" variant="outline" onClick={() => setPaying(row)}><WalletCards data-icon="inline-start" aria-hidden="true" />Pay</Button> : null}<Button size="icon-sm" variant="ghost" aria-label={`Download ${row.number} PDF`} onClick={() => download(row)}><Download aria-hidden="true" /></Button>{!["draft", "voided"].includes(row.status) && canApprove ? <Button size="icon-sm" variant="ghost" aria-label={`Void ${row.number}`} onClick={() => action.mutate({ document: row, action: "void" })}><Ban aria-hidden="true" /></Button> : null}</div> },
      ]} />}
    </CardContent></Card>
    <PaymentDialog document={paying} accounts={(accounts.data?.data ?? []).filter((account) => account.is_bank)} busy={action.isPending} onOpenChange={(next) => { if (!next) setPaying(null); }} onSubmit={(payload) => { if (paying) action.mutate({ document: paying, action: "pay", payload }); }} />
  </FinanceShell>;
}

function DocumentDialog({ group, open, onOpenChange, contacts, accounts, busy, onSubmit }: { group: "sales" | "purchases"; open: boolean; onOpenChange: (open: boolean) => void; contacts: FinanceContact[]; accounts: FinanceAccount[]; busy: boolean; onSubmit: (payload: Record<string, unknown>) => void }) {
  const [lineIds, setLineIds] = useState([0]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const items = lineIds.map((id) => ({ description: values.get(`description_${id}`), quantity: Number(values.get(`quantity_${id}`) || 1), unit_price: Number(values.get(`unit_price_${id}`) || 0), discount: Number(values.get(`discount_${id}`) || 0), tax_rate: Number(values.get(`tax_rate_${id}`) || 0), account_id: values.get(`account_${id}`) ? Number(values.get(`account_${id}`)) : undefined })); onSubmit({ type: values.get("type"), contact_id: values.get("contact_id") ? Number(values.get("contact_id")) : null, document_date: values.get("document_date"), due_date: values.get("due_date") || null, currency: values.get("currency") || "ETB", bank_account_id: values.get("bank_account_id") ? Number(values.get("bank_account_id")) : null, reference: values.get("reference") || null, goods_receipt_reference: values.get("goods_receipt_reference") || null, tax_invoice_type: values.get("tax_invoice_type") || "standard", supply_category: values.get("supply_category") || "goods", payment_method: values.get("payment_method") || null, notes: values.get("notes") || null, items }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogTrigger asChild><Button><Plus data-icon="inline-start" aria-hidden="true" />New document</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-4xl"><form onSubmit={submit} className="flex flex-col gap-5"><DialogHeader><DialogTitle>Create {group === "sales" ? "sales" : "purchase"} document</DialogTitle><DialogDescription>Totals and VAT are calculated by the server from the line details. Required fields are marked.</DialogDescription></DialogHeader><FieldGroup>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field><FieldLabel htmlFor="document-type">Document type (required)</FieldLabel><NativeSelect id="document-type" name="type" required defaultValue={types[group][0][0]}>{types[group].map(([value, label]) => <NativeSelectOption key={value} value={value}>{label}</NativeSelectOption>)}</NativeSelect></Field><Field><FieldLabel htmlFor="document-contact">{group === "sales" ? "Customer" : "Vendor"}</FieldLabel><NativeSelect id="document-contact" name="contact_id" defaultValue=""><NativeSelectOption value="">Not assigned</NativeSelectOption>{contacts.map((contact) => <NativeSelectOption key={contact.id} value={String(contact.id)}>{contact.code} · {contact.name}</NativeSelectOption>)}</NativeSelect></Field><Field><FieldLabel htmlFor="document-date">Document date (required)</FieldLabel><Input id="document-date" name="document_date" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></Field><Field><FieldLabel htmlFor="document-due">Due date</FieldLabel><Input id="document-due" name="due_date" type="date" /></Field></div>
    <div className="grid gap-4 sm:grid-cols-3"><Field><FieldLabel htmlFor="document-reference">Reference</FieldLabel><Input id="document-reference" name="reference" /></Field><Field><FieldLabel htmlFor="document-currency">Currency</FieldLabel><Input id="document-currency" name="currency" defaultValue="ETB" maxLength={3} /></Field><Field><FieldLabel htmlFor="document-bank">Cash or bank account</FieldLabel><NativeSelect id="document-bank" name="bank_account_id" defaultValue=""><NativeSelectOption value="">Use system default</NativeSelectOption>{accounts.filter((account) => account.is_bank).map((account) => <NativeSelectOption key={account.id} value={String(account.id)}>{account.code} · {account.name}</NativeSelectOption>)}</NativeSelect></Field></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field><FieldLabel htmlFor="document-tax-invoice-type">Tax invoice type</FieldLabel><NativeSelect id="document-tax-invoice-type" name="tax_invoice_type" defaultValue="standard"><NativeSelectOption value="standard">Standard tax invoice</NativeSelectOption><NativeSelectOption value="simplified">Simplified cash or retail invoice</NativeSelectOption><NativeSelectOption value="recipient_created">Recipient-created invoice</NativeSelectOption><NativeSelectOption value="reverse_charge">Reverse-charge invoice</NativeSelectOption></NativeSelect></Field><Field><FieldLabel htmlFor="document-supply-category">Supply category</FieldLabel><NativeSelect id="document-supply-category" name="supply_category" defaultValue="goods"><NativeSelectOption value="goods">Goods</NativeSelectOption><NativeSelectOption value="services">Services</NativeSelectOption></NativeSelect></Field><Field><FieldLabel htmlFor="document-payment-method">Expected payment method</FieldLabel><NativeSelect id="document-payment-method" name="payment_method" defaultValue="bank_transfer"><NativeSelectOption value="bank_transfer">Bank transfer</NativeSelectOption><NativeSelectOption value="account_payee_cheque">Account-payee cheque</NativeSelectOption><NativeSelectOption value="nbe_authorized">NBE-authorized payment</NativeSelectOption><NativeSelectOption value="cash">Cash</NativeSelectOption></NativeSelect></Field><Field><FieldLabel htmlFor="document-goods-receipt">Goods receipt reference</FieldLabel><Input id="document-goods-receipt" name="goods_receipt_reference" /><FieldDescription>Required with a purchase-order reference for three-way matching.</FieldDescription></Field></div>
    <FieldSet><FieldLegend>Document lines (required)</FieldLegend><FieldDescription>Add item descriptions, quantities, unit prices, discounts, and VAT rates. Purchase lines can target a specific expense or inventory account.</FieldDescription><div className="flex flex-col gap-4">{lineIds.map((id, index) => <Card key={id}><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>Line {index + 1}</CardTitle>{lineIds.length > 1 ? <Button type="button" variant="ghost" size="sm" onClick={() => setLineIds((current) => current.filter((value) => value !== id))}><Trash2 data-icon="inline-start" aria-hidden="true" />Remove</Button> : null}</div></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">
      <Field className="lg:col-span-2"><FieldLabel htmlFor={`document-description-${id}`}>Description (required)</FieldLabel><Input id={`document-description-${id}`} name={`description_${id}`} required /></Field><Field><FieldLabel htmlFor={`document-quantity-${id}`}>Quantity</FieldLabel><Input id={`document-quantity-${id}`} name={`quantity_${id}`} type="number" min="0.001" step="0.001" defaultValue="1" required /></Field><Field><FieldLabel htmlFor={`document-price-${id}`}>Unit price</FieldLabel><Input id={`document-price-${id}`} name={`unit_price_${id}`} type="number" min="0" step="0.01" defaultValue="0" required /></Field><Field><FieldLabel htmlFor={`document-discount-${id}`}>Discount</FieldLabel><Input id={`document-discount-${id}`} name={`discount_${id}`} type="number" min="0" step="0.01" defaultValue="0" /></Field><Field><FieldLabel htmlFor={`document-tax-${id}`}>VAT %</FieldLabel><Input id={`document-tax-${id}`} name={`tax_rate_${id}`} type="number" min="0" max="100" step="0.01" defaultValue="0" /></Field>{group === "purchases" ? <Field className="lg:col-span-3"><FieldLabel htmlFor={`document-account-${id}`}>Posting account</FieldLabel><NativeSelect id={`document-account-${id}`} name={`account_${id}`} defaultValue=""><NativeSelectOption value="">Operating expense default</NativeSelectOption>{accounts.filter((account) => ["asset", "expense"].includes(account.type)).map((account) => <NativeSelectOption key={account.id} value={String(account.id)}>{account.code} · {account.name}</NativeSelectOption>)}</NativeSelect></Field> : null}
    </CardContent></Card>)}</div><Button type="button" variant="outline" onClick={() => setLineIds((current) => [...current, Math.max(...current) + 1])}><Plus data-icon="inline-start" aria-hidden="true" />Add line</Button></FieldSet>
    <Field><FieldLabel htmlFor="document-notes">Notes</FieldLabel><Input id="document-notes" name="notes" /></Field>
  </FieldGroup><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={busy}><BusyLabel busy={busy}>Create document</BusyLabel></Button></DialogFooter></form></DialogContent></Dialog>;
}

function PaymentDialog({ document, accounts, busy, onOpenChange, onSubmit }: { document: FinanceDocument | null; accounts: FinanceAccount[]; busy: boolean; onOpenChange: (open: boolean) => void; onSubmit: (payload: Record<string, unknown>) => void }) {
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); onSubmit({ amount: Number(values.get("amount")), bank_account_id: Number(values.get("bank_account_id")), payment_method: values.get("payment_method") || "bank_transfer" }); }
  const remaining = document ? Number(document.total) - Number(document.paid_amount) : 0;
  return <Dialog open={Boolean(document)} onOpenChange={onOpenChange}><DialogContent><form onSubmit={submit} className="flex flex-col gap-5"><DialogHeader><DialogTitle>Record payment</DialogTitle><DialogDescription>Apply a payment to {document?.number}. The remaining balance is <Money value={remaining} currency={document?.currency} />. Cash above the configured Ethiopian limit is blocked.</DialogDescription></DialogHeader><FieldGroup><Field><FieldLabel htmlFor="payment-amount">Payment amount (required)</FieldLabel><Input id="payment-amount" name="amount" type="number" min="0.01" max={remaining} step="0.01" defaultValue={remaining} required autoFocus /></Field><Field><FieldLabel htmlFor="payment-bank">Cash or bank account (required)</FieldLabel><NativeSelect id="payment-bank" name="bank_account_id" required defaultValue=""><NativeSelectOption value="" disabled>Select an account</NativeSelectOption>{accounts.map((account) => <NativeSelectOption key={account.id} value={String(account.id)}>{account.code} · {account.name}</NativeSelectOption>)}</NativeSelect></Field><Field><FieldLabel htmlFor="payment-method">Payment method (required)</FieldLabel><NativeSelect id="payment-method" name="payment_method" required defaultValue={document?.payment_method ?? "bank_transfer"}><NativeSelectOption value="bank_transfer">Bank transfer</NativeSelectOption><NativeSelectOption value="account_payee_cheque">Account-payee cheque</NativeSelectOption><NativeSelectOption value="nbe_authorized">NBE-authorized payment</NativeSelectOption><NativeSelectOption value="cash">Cash</NativeSelectOption></NativeSelect></Field></FieldGroup><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={busy || accounts.length === 0}><BusyLabel busy={busy}>Record payment</BusyLabel></Button></DialogFooter></form></DialogContent></Dialog>;
}
