"use client";

import { useState, type FormEvent } from "react";
import { Check, LockKeyhole, PlugZap, Plus, Send, X } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { usePermissions } from "@/hooks/use-permissions";
import { financeApi } from "@/modules/finance/api";
import type { FinancePeriod } from "@/modules/finance/types";
import { BusyLabel, FinanceError, FinanceLoading, FinanceShell, FinanceStatus, FinanceTable } from "@/modules/finance/pages/components/finance-shell";

export default function FinanceSettingsPage() {
  const client = useQueryClient(); const { hasAnyPermission } = usePermissions(); const [unlocking, setUnlocking] = useState<FinancePeriod | null>(null);
  const canManage = hasAnyPermission(["manage_finance", "manage_finance_settings"]); const canPeriods = hasAnyPermission(["manage_finance", "manage_fiscal_periods"]); const canIntegrate = hasAnyPermission(["manage_finance", "manage_finance_integrations"]); const canApproveUnlock = hasAnyPermission(["manage_finance", "approve_finance_unlocks"]);
  const query = useQuery({ queryKey: ["finance", "settings"], queryFn: financeApi.settings });
  const refresh = () => client.invalidateQueries({ queryKey: ["finance"] });
  const tax = useMutation({ mutationFn: financeApi.createTaxRate, onSuccess: async () => { await refresh(); toast.success("Tax rate created."); }, onError: () => toast.error("Tax rate could not be created.") });
  const period = useMutation({ mutationFn: financeApi.createPeriod, onSuccess: async () => { await refresh(); toast.success("Fiscal period created."); }, onError: () => toast.error("Fiscal period could not be created.") });
  const periodAction = useMutation({ mutationFn: ({ id, action }: { id: number; action: "lock" | "close" }) => financeApi.periodAction(id, action), onSuccess: async () => { await refresh(); toast.success("Fiscal period updated."); }, onError: () => toast.error("Fiscal period could not be updated.") });
  const unlock = useMutation({ mutationFn: ({ id, reason }: { id: number; reason: string }) => financeApi.requestUnlock(id, reason), onSuccess: async () => { await refresh(); setUnlocking(null); toast.success("Unlock request submitted."); }, onError: () => toast.error("Unlock request could not be submitted.") });
  const review = useMutation({ mutationFn: ({ id, decision }: { id: number; decision: "approved" | "rejected" }) => financeApi.reviewUnlock(id, decision), onSuccess: async () => { await refresh(); toast.success("Unlock request reviewed."); }, onError: () => toast.error("Unlock request could not be reviewed.") });
  const mapping = useMutation({ mutationFn: financeApi.saveMapping, onSuccess: async () => { await refresh(); toast.success("Account mapping saved."); }, onError: () => toast.error("Account mapping could not be saved.") });
  const sync = useMutation({ mutationFn: financeApi.syncHospitality, onSuccess: async (data) => { await refresh(); toast.success(`${data.processed} Hospitality posting(s) synchronized.`); }, onError: () => toast.error("Hospitality postings could not be synchronized.") });
  return <FinanceShell title="Finance settings" description="Configure VAT, fiscal periods, source-module account mappings, unlock governance, and posting integrations without weakening ledger controls.">
    {query.isLoading ? <FinanceLoading /> : query.error || !query.data ? <FinanceError error={query.error} /> : <>
      <div className="grid gap-6 xl:grid-cols-2">
        <Card><CardHeader><CardTitle><h2 className="text-base font-semibold">Tax rates</h2></CardTitle><CardDescription>VAT and other tax rates available to financial document lines.</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><FinanceTable caption="Configured tenant tax rates." rows={query.data.tax_rates} getKey={(row) => row.id} columns={[
          { key: "code", label: "Code", render: (row) => <span className="font-mono">{row.code}</span> }, { key: "name", label: "Tax", render: (row) => row.name }, { key: "rate", label: "Rate", align: "right", render: (row) => `${Number(row.rate).toFixed(2)}%` }, { key: "status", label: "Status", render: (row) => <FinanceStatus value={row.is_active ? "active" : "inactive"} /> },
        ]} />{canManage ? <TaxForm busy={tax.isPending} onSubmit={(payload) => tax.mutate(payload)} /> : null}</CardContent></Card>

        <Card><CardHeader><CardTitle><h2 className="text-base font-semibold">Fiscal periods</h2></CardTitle><CardDescription>Lock periods to prevent back-posting. Reopening requires a reviewed unlock request.</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><FinanceTable<FinancePeriod> caption="Tenant fiscal posting periods." rows={query.data.periods} getKey={(row) => row.id} columns={[
          { key: "name", label: "Period", render: (row) => <span className="font-medium">{row.name}</span> }, { key: "dates", label: "Dates", render: (row) => `${row.starts_on} – ${row.ends_on}` }, { key: "status", label: "Status", render: (row) => <FinanceStatus value={row.status} /> }, { key: "actions", label: "Actions", align: "right", render: (row) => <div className="flex justify-end gap-1">{row.status === "open" && canPeriods ? <Button size="sm" onClick={() => periodAction.mutate({ id: row.id, action: "lock" })}><LockKeyhole data-icon="inline-start" aria-hidden="true" />Lock</Button> : null}{row.status === "locked" ? <Button size="sm" variant="outline" onClick={() => setUnlocking(row)}><Send data-icon="inline-start" aria-hidden="true" />Request unlock</Button> : null}{row.status === "locked" && canPeriods ? <Button size="sm" variant="ghost" onClick={() => periodAction.mutate({ id: row.id, action: "close" })}>Close</Button> : null}</div> },
        ]} />{canPeriods ? <PeriodForm busy={period.isPending} onSubmit={(payload) => period.mutate(payload)} /> : null}</CardContent></Card>
      </div>

      <Card><CardHeader><CardTitle><h2 className="text-base font-semibold">Period unlock requests</h2></CardTitle><CardDescription>Every request retains the requester, reason, reviewer, decision, and timestamp.</CardDescription></CardHeader><CardContent><FinanceTable<Record<string, unknown>> caption="Recent fiscal period unlock requests." rows={query.data.unlock_requests} getKey={(row) => Number(row.id)} columns={[
        { key: "period", label: "Period", render: (row) => String((row.period as { name?: string } | undefined)?.name ?? row.period_id) }, { key: "reason", label: "Reason", render: (row) => String(row.reason) }, { key: "status", label: "Status", render: (row) => <FinanceStatus value={String(row.status)} /> }, { key: "actions", label: "Review", align: "right", render: (row) => row.status === "pending" && canApproveUnlock ? <div className="flex justify-end gap-1"><Button size="sm" onClick={() => review.mutate({ id: Number(row.id), decision: "approved" })}><Check data-icon="inline-start" aria-hidden="true" />Approve</Button><Button size="sm" variant="outline" onClick={() => review.mutate({ id: Number(row.id), decision: "rejected" })}><X data-icon="inline-start" aria-hidden="true" />Reject</Button></div> : <span className="text-muted-foreground">Reviewed</span> },
      ]} /></CardContent></Card>

      <div className="grid gap-6 xl:grid-cols-2">
        <Card><CardHeader><CardTitle><h2 className="text-base font-semibold">Source account mappings</h2></CardTitle><CardDescription>Map a source module event to a default debit and credit account.</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><FinanceTable<Record<string, unknown>> caption="Cross-module posting mappings." rows={query.data.account_mappings} getKey={(row) => Number(row.id)} columns={[
          { key: "source", label: "Source", render: (row) => `${row.source_module} · ${row.event}` }, { key: "debit", label: "Debit", render: (row) => String((row.debit_account as { code?: string; name?: string } | undefined)?.code ?? row.debit_account_id) }, { key: "credit", label: "Credit", render: (row) => String((row.credit_account as { code?: string; name?: string } | undefined)?.code ?? row.credit_account_id) }, { key: "status", label: "Status", render: (row) => <FinanceStatus value={row.is_active ? "active" : "inactive"} /> },
        ]} />{canIntegrate ? <MappingForm accounts={query.data.system_accounts} busy={mapping.isPending} onSubmit={(payload) => mapping.mutate(payload)} /> : null}</CardContent></Card>
        <Card><CardHeader><CardTitle><h2 className="text-base font-semibold">Operational integrations</h2></CardTitle><CardDescription>Bring tenant events into the ledger with an idempotency key, source reference, and balanced journal.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><Alert><PlugZap aria-hidden="true" /><AlertTitle>Hospitality settlement bridge</AlertTitle><AlertDescription>Synchronizes posted restaurant and hospitality settlement payloads. Re-running is safe because source events are idempotent.</AlertDescription></Alert></CardContent>{canIntegrate ? <CardFooter><Button disabled={sync.isPending} onClick={() => sync.mutate()}><BusyLabel busy={sync.isPending}>Sync Hospitality postings</BusyLabel></Button></CardFooter> : null}</Card>
      </div>
    </>}
    <UnlockDialog period={unlocking} busy={unlock.isPending} onOpenChange={(open) => { if (!open) setUnlocking(null); }} onSubmit={(reason) => { if (unlocking) unlock.mutate({ id: unlocking.id, reason }); }} />
  </FinanceShell>;
}

function TaxForm({ busy, onSubmit }: { busy: boolean; onSubmit: (payload: Record<string, unknown>) => void }) { function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); onSubmit({ name: values.get("name"), code: values.get("code"), rate: Number(values.get("rate")), kind: "vat", is_inclusive: values.get("inclusive") === "1", is_active: true }); event.currentTarget.reset(); } return <form onSubmit={submit} className="rounded-xl border p-4"><FieldGroup><div className="grid gap-4 sm:grid-cols-3"><Field><FieldLabel htmlFor="tax-name">Tax name (required)</FieldLabel><Input id="tax-name" name="name" required /></Field><Field><FieldLabel htmlFor="tax-code">Code (required)</FieldLabel><Input id="tax-code" name="code" required /></Field><Field><FieldLabel htmlFor="tax-rate">Rate % (required)</FieldLabel><Input id="tax-rate" name="rate" type="number" min="0" max="100" step="0.0001" required /></Field></div><Field><FieldLabel htmlFor="tax-inclusive">Price treatment</FieldLabel><NativeSelect id="tax-inclusive" name="inclusive" defaultValue="0"><NativeSelectOption value="0">Tax exclusive</NativeSelectOption><NativeSelectOption value="1">Tax inclusive</NativeSelectOption></NativeSelect></Field><Button type="submit" disabled={busy}><Plus data-icon="inline-start" aria-hidden="true" /><BusyLabel busy={busy}>Add tax rate</BusyLabel></Button></FieldGroup></form>; }

function PeriodForm({ busy, onSubmit }: { busy: boolean; onSubmit: (payload: Record<string, unknown>) => void }) { function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); onSubmit({ name: values.get("name"), starts_on: values.get("starts_on"), ends_on: values.get("ends_on") }); event.currentTarget.reset(); } return <form onSubmit={submit} className="rounded-xl border p-4"><FieldGroup><Field><FieldLabel htmlFor="period-name">Period name (required)</FieldLabel><Input id="period-name" name="name" required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="period-start">Start date (required)</FieldLabel><Input id="period-start" name="starts_on" type="date" required /></Field><Field><FieldLabel htmlFor="period-end">End date (required)</FieldLabel><Input id="period-end" name="ends_on" type="date" required /></Field></div><Button type="submit" disabled={busy}><Plus data-icon="inline-start" aria-hidden="true" /><BusyLabel busy={busy}>Add fiscal period</BusyLabel></Button></FieldGroup></form>; }

function MappingForm({ accounts, busy, onSubmit }: { accounts: Array<{ id: number; code: string; name: string }>; busy: boolean; onSubmit: (payload: Record<string, unknown>) => void }) { function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); onSubmit({ source_module: values.get("source_module"), event: values.get("event"), debit_account_id: Number(values.get("debit_account_id")), credit_account_id: Number(values.get("credit_account_id")), is_active: true }); } return <form onSubmit={submit} className="rounded-xl border p-4"><FieldGroup><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="mapping-module">Source module (required)</FieldLabel><Input id="mapping-module" name="source_module" placeholder="Example: payroll" required /></Field><Field><FieldLabel htmlFor="mapping-event">Event (required)</FieldLabel><Input id="mapping-event" name="event" placeholder="Example: payroll_posted" required /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="mapping-debit">Debit account (required)</FieldLabel><NativeSelect id="mapping-debit" name="debit_account_id" required defaultValue=""><NativeSelectOption value="" disabled>Select account</NativeSelectOption>{accounts.map((account) => <NativeSelectOption key={account.id} value={String(account.id)}>{account.code} · {account.name}</NativeSelectOption>)}</NativeSelect></Field><Field><FieldLabel htmlFor="mapping-credit">Credit account (required)</FieldLabel><NativeSelect id="mapping-credit" name="credit_account_id" required defaultValue=""><NativeSelectOption value="" disabled>Select account</NativeSelectOption>{accounts.map((account) => <NativeSelectOption key={account.id} value={String(account.id)}>{account.code} · {account.name}</NativeSelectOption>)}</NativeSelect></Field></div><Button type="submit" disabled={busy || accounts.length === 0}><BusyLabel busy={busy}>Save mapping</BusyLabel></Button></FieldGroup></form>; }

function UnlockDialog({ period, busy, onOpenChange, onSubmit }: { period: FinancePeriod | null; busy: boolean; onOpenChange: (open: boolean) => void; onSubmit: (reason: string) => void }) { function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSubmit(String(new FormData(event.currentTarget).get("reason"))); } return <Dialog open={Boolean(period)} onOpenChange={onOpenChange}><DialogContent><form onSubmit={submit} className="flex flex-col gap-5"><DialogHeader><DialogTitle>Request fiscal period unlock</DialogTitle><DialogDescription>Explain why {period?.name} must reopen. A finance controller must review the request before postings are allowed.</DialogDescription></DialogHeader><Field><FieldLabel htmlFor="unlock-reason">Reason (required)</FieldLabel><Input id="unlock-reason" name="reason" required minLength={10} autoFocus /><FieldDescription>Include the affected document or journal reference and the correction required.</FieldDescription></Field><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={busy}><BusyLabel busy={busy}>Submit request</BusyLabel></Button></DialogFooter></form></DialogContent></Dialog>; }
