import { ClipboardCheck, LayoutDashboard, Package, PackageSearch, Shapes, Tags, Truck } from "lucide-react";
import type { FrontendModuleDefinition } from "@/modules/types";

export const inventoryModule: FrontendModuleDefinition = {
  id: "inventory",
  name: "Inventory",
  description: "Digitized inventory catalog and stock operations for lounge, club, and upcoming modules.",
  backendModule: "Modules\\Inventory",
  routePrefixes: [
    "/dashboard/inventory",
    "/dashboard/inventory/inventory",
    "/dashboard/inventory/qa",
    "/dashboard/inventory/catalog/categories",
    "/dashboard/inventory/catalog/tags",
    "/dashboard/inventory/catalog/products",
    "/dashboard/inventory/catalog/suppliers",
    "/dashboard/inventory/documents",
  ],
  navItems: [
    {
      moduleId: "inventory",
      translationKey: "nav.inventory",
      fallbackLabel: "Inventory Dashboard",
      href: "/dashboard/inventory",
      icon: LayoutDashboard,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
      tourId: "tour-nav-inventory",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_items",
      fallbackLabel: "Inventory Items",
      href: "/dashboard/inventory/inventory",
      icon: Package,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_categories",
      fallbackLabel: "Product Categories",
      href: "/dashboard/inventory/catalog/categories",
      icon: Shapes,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_tags",
      fallbackLabel: "Product Tags",
      href: "/dashboard/inventory/catalog/tags",
      icon: Tags,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_products",
      fallbackLabel: "Products",
      href: "/dashboard/inventory/catalog/products",
      icon: PackageSearch,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_suppliers",
      fallbackLabel: "Suppliers",
      href: "/dashboard/inventory/catalog/suppliers",
      icon: Truck,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_qa",
      fallbackLabel: "Quality Assurance",
      href: "/dashboard/inventory/qa",
      icon: ClipboardCheck,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      businessTypes: ["water-bottling"],
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_documents",
      fallbackLabel: "Inventory Documents",
      href: "/dashboard/inventory/documents",
      icon: LayoutDashboard, // Will use a better icon if found, for now LayoutDashboard
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
  ],
};
