"use client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
type Props={postings:any[];applicants:any[];attempts:any[];api:(path:string,options?:RequestInit)=>Promise<any>;refresh:()=>Promise<void>;setStatus:(v:string)=>void;setError:(v:string)=>void};
export function CommitteeReviewPanel({postings,applicants,attempts,api,refresh,setStatus,setError}:Props){
 async function committee(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,v=Object.fromEntries(new FormData(form));const members=String(v.user_ids).split(",").map(x=>Number(x.trim())).filter(Boolean).map((user_id,index)=>({user_id,role:index===0?"chair":"assessor",weight:1}));try{await api("/job-postings/"+v.job_posting_id+"/committee",{method:"PUT",body:JSON.stringify({members})});setStatus("Recruitment committee saved.");form.reset()}catch(x){setError(x instanceof Error?x.message:"Committee was not saved.")}}
 async function review(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,v=Object.fromEntries(new FormData(form));try{await api("/applicants/"+v.applicant_id+"/review",{method:"PUT",body:JSON.stringify({score:Number(v.score),strengths:v.strengths,concerns:v.concerns,recommendation:v.recommendation})});setStatus("Your candidate review was saved.");form.reset();refresh()}catch(x){setError(x instanceof Error?x.message:"Review was not saved.")}}
 async function grade(e:React.FormEvent<HTMLFormElement>,attempt:any){e.preventDefault();const v=new FormData(e.currentTarget);const answers=(attempt.answers||[]).map((answer:any)=>({question_id:answer.question_id,score:Number(v.get("score-"+answer.question_id)||0),review_note:String(v.get("note-"+answer.question_id)||"")}));try{await api("/assessment-attempts/"+attempt.id+"/grade",{method:"POST",body:JSON.stringify({answers})});setStatus("Assessment grading saved.");refresh()}catch(x){setError(x instanceof Error?x.message:"Grades were not saved.")}}
 return <div className="grid gap-6 xl:grid-cols-2"><div className="space-y-6">
  <form onSubmit={committee} className="space-y-4 rounded-2xl border bg-card p-6"><h2 className="text-xl font-black">Recruitment committee</h2><p className="text-sm text-muted-foreground">The first user becomes chair; remaining users become assessors. Use tenant user IDs from User Management.</p><div><Label htmlFor="committee-job">Vacancy</Label><select id="committee-job" name="job_posting_id" required className="min-h-11 w-full rounded-md border bg-background px-3"><option value="">Choose vacancy…</option>{postings.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></div><div><Label htmlFor="committee-users">Committee user IDs</Label><Input id="committee-users" name="user_ids" required placeholder="12, 18, 25" aria-describedby="committee-users-hint"/><p id="committee-users-hint" className="mt-1 text-xs text-muted-foreground">Comma-separated tenant user IDs.</p></div><Button type="submit">Save committee</Button></form>
  <form onSubmit={review} className="space-y-4 rounded-2xl border bg-card p-6"><h2 className="text-xl font-black">Committee candidate review</h2><div><Label htmlFor="review-applicant">Candidate</Label><select id="review-applicant" name="applicant_id" required className="min-h-11 w-full rounded-md border bg-background px-3"><option value="">Choose candidate…</option>{applicants.map(a=><option key={a.id} value={a.id}>{a.candidate_name} — {a.job_posting?.title}</option>)}</select></div><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="review-score">Score out of 100</Label><Input id="review-score" name="score" type="number" min="0" max="100" required/></div><div><Label htmlFor="review-recommendation">Recommendation</Label><select id="review-recommendation" name="recommendation" required className="min-h-11 w-full rounded-md border bg-background px-3"><option value="strong_yes">Strong yes</option><option value="yes">Yes</option><option value="hold">Hold</option><option value="no">No</option></select></div></div><div><Label htmlFor="review-strengths">Strengths</Label><textarea id="review-strengths" name="strengths" rows={3} className="w-full rounded-md border bg-background p-3"/></div><div><Label htmlFor="review-concerns">Concerns</Label><textarea id="review-concerns" name="concerns" rows={3} className="w-full rounded-md border bg-background p-3"/></div><Button type="submit">Save my review</Button></form>
 </div><section className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-black">Manual assessment grading</h2><p className="mt-1 text-sm text-muted-foreground">Review essays and code, then award points. Objective scores remain automatic.</p><div className="mt-5 space-y-4">{attempts.filter(a=>a.status==="submitted"||a.status==="graded").map(attempt=><details key={attempt.id} className="rounded-xl border p-4"><summary className="min-h-11 cursor-pointer font-bold">{attempt.invitation.applicant.candidate_name} · {attempt.invitation.assessment.title}</summary><form onSubmit={e=>grade(e,attempt)} className="mt-4 space-y-4">{(attempt.answers||[]).map((answer:any)=><fieldset key={answer.id} className="rounded-lg border p-4"><legend className="px-2 font-semibold">{answer.question?.prompt||"Assessment answer"}</legend><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(answer.answer,null,2)}</pre><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Label htmlFor={"grade-"+attempt.id+"-"+answer.question_id}>Manual score</Label><Input id={"grade-"+attempt.id+"-"+answer.question_id} name={"score-"+answer.question_id} type="number" min="0" max={Number(answer.question?.points||100)} defaultValue={answer.manual_score??answer.auto_score??0}/></div><div><Label htmlFor={"note-"+attempt.id+"-"+answer.question_id}>Review note</Label><Input id={"note-"+attempt.id+"-"+answer.question_id} name={"note-"+answer.question_id} defaultValue={answer.review_note||""}/></div></div></fieldset>)}<Button type="submit">Save grades</Button></form></details>)}</div></section></div>
}
